### ISSUE TITLE
Create Deploying with Chef section about how to install, configure and deploy with Chef

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-documentation#1374]
Hi team,

We don't have a guide about how to use Chef to install Wazuh yet.

In order to upgrade the documentation to show users how to use our Chef repository some tasks must be done:

#### Tasks

- [ ]  Create the structure of the Deploying with Chef guide

- [ ] Add Chef installation guide

- [ ] Implement how to install and configure Wazuh cookbooks on Chef.

- [ ] Add deployment instruction to install Wazuh 

- [ ] Verify syntax and grammar

- [ ] Compile documentation

Best regards,

Jose
