### ISSUE TITLE
Write new documentation for the Wazuh app

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#203]
We finished the first stage of Wazuh app documentation. We still need to write more articles, so the community can have more information about how to use the app.

### Tasks:
- [x] Write an article with the package list for the Wazuh App.
- [x] Write an article to fully customize the Wazuh alerts to use a completely different template and pattern.
- [x] Write an article for the config.yml file, describing the current parameters, checks, extensions, what it does, etc. Everything related to the configuration since this file will be more complex in the future.
- [x] Write the troubleshooting guide, collecting all the solutions we've provided to the users on the mailing lists and writing them in an article.
- [x] Articles for installation, extensions, X-Pack, adding an API, etc.
- [x] Minor enhancements for currently existing Wazuh app documentation articles.
- [x] Write a new documentation section with common Wazuh App problems and their best possible solutions. Collect all the notes from helping on the mailing lists and elaborate a collaborative document.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Working on this issue in [this branch](https://github.com/wazuh/wazuh-documentation/tree/3.2-wazuh-app-docs).

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
May 21st update: We've moved the old app articles to the new section, and we've written the config file reference article, describing all the available options.

We're now working on the dedicated articles for each Wazuh app tab.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Added the following content to the _How to use_ section including screenshots:

- Agents preview
- Agent
- Dev tools
- Discover
- Settings

Regards,
Jesús

**Comment by jesusgn90** [comment]
Added the following content to the How to use section including screenshots:

- Lists
- Overview

Completed the following content from _How to use > Manager_:

- Manager
  - Ruleset
  - Status
  - Groups
  - Logs
  - Configuration

Added content to Troubleshooting section.

Regards,
Jesús

**Comment by havidarou** [comment]
Reviewing documentation.

**Comment by havidarou** [comment]
After reviewing documentation, I will propose a new structure for it trying to depict specific features instead of an extensive overview showcase.

**Comment by JuanjiJG** [comment]
First version done at #283.

This issue is not finished yet, we can still improve this documentation.

Regards,
Juanjo

**Comment by havidarou** [comment]
Reviewing first approach.

Changing arrows and text in screenshots.

**Comment by JuanjiJG** [comment]
Before continuing with this issue, we must decide what are the articles we're going to write for the documentation.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
**November 21st update**

- Added a new article to change the name of Elasticsearch indices.
- `Write an article for updating the app, describing the correct steps.` doesn't make any sense for now. We already have the upgrading guides. We can elaborate this more in the future on a new issue.
- `Write an article with the package list for the Wazuh App.` is ready because now we have a table on the packages list with the Kibana and Splunk apps.

**Comment by JuanjiJG** [comment]
Done here: #656.

Regards,
Juanjo
