### ISSUE TITLE
New documentation structure review

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#2205]
Hello team

  The branch `new-documentation-structure` needs to be reviewed. @jctello, @dkempny  and @davidfmiranda, thanks for proposing changes. 

Best regards, 
Alberto R

**Comment by davidfmiranda** [comment]
Hello team
Yesterday I started reviewing Installation Guide's introduction and Elastic Search single node cluster.
Today I will be reviewing elasticsearch multinode cluster

**Comment by alberpilot** [comment]
@davidfmiranda please review the following:

![image](https://user-images.githubusercontent.com/3830293/75143007-81540e80-56f4-11ea-89cc-445e3d469f8f.png)

**Comment by alberpilot** [comment]
@davidfmiranda please review the Jumpstart to Wazuh guide and the Installation guide searching for Debian 7/Ubuntu 12 notes and remove them.

**Comment by alberpilot** [comment]
Hello team

 The certificates generation command shows 5 Warnings:

![image](https://user-images.githubusercontent.com/3830293/75143901-3affaf00-56f6-11ea-8e50-750cc1cfbb82.png)

Please investigate if we can avoid them.

**Comment by alberpilot** [comment]
Another one:

All places where: 
![image](https://user-images.githubusercontent.com/3830293/75149569-9fc10680-5702-11ea-9b3c-ebceb1af3efc.png) must be updated, we need to explain that the password is the `elastic` user password.

**Comment by alberpilot** [comment]
Another one: 

![image](https://user-images.githubusercontent.com/3830293/75149654-db5bd080-5702-11ea-8806-948e6553e29f.png)

Could we generate only the `elastic` user password?

**Comment by alberpilot** [comment]
Another one: please review the Kibana plugin installation step. Remove the local file installation option, only the http will be taken into account.

**Comment by alberpilot** [comment]
![image](https://user-images.githubusercontent.com/3830293/75150013-a439ef00-5703-11ea-88f9-e91cceef939e.png)

Please check if this is necessary or can be removed.

**Comment by alberpilot** [comment]
![image](https://user-images.githubusercontent.com/3830293/75150181-19a5bf80-5704-11ea-93f4-bfa466bb48af.png)
 
Please review the order of the parameters.

**Comment by alberpilot** [comment]
![image](https://user-images.githubusercontent.com/3830293/75150782-6b027e80-5705-11ea-99bb-0007c3dc6aba.png)

This needs to be explained. Why and how.

**Comment by dkempny** [comment]
`Getting started` -> `Compatibility matrix` - `Product compatibility` may leave confusion for two reasons:

1. Section header: `API and Wazuh Kibana plugin` and table header `API and Wazuh App version` doesn't match. The documentation uses Wazuh App, Wazuh Kibana Plugin, and Wazuh Plugin interchangeably. 
http://10.0.0.12/new-documentation-structure/getting-started/compatibility_matrix/index.html#api-and-wazuh-kibana-plugin
2. Table content is not accurate and does not include Wazuh App v3.11.x. Could we use a similar table as in GitHub: https://github.com/wazuh/wazuh-kibana-app#older-packages ? In the documentation, there is this link provided, but the first source of information would be an incorrect table content.

**Comment by dkempny** [comment]
Regarding: https://github.com/wazuh/wazuh-documentation/issues/2205#issuecomment-590249583

The issue is described on Elastic: https://github.com/elastic/elasticsearch/issues/48879 and looks like it is still ongoing.

I was trying to silence the `warnings` using `--silence` parameter (https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html), but it only removes additional info leaving warnings as they were before.

**Comment by dkempny** [comment]
Pull request: #2245

The structure of Wazuh - Elastic Stack environment is well explained in `Installation Guide` -> `Introduction`, but when we move to the `Installation` -> `Elasticsearch single-node cluster installation` and choose `Wazuh single-node cluster` tab, Filebeat host IP might leave some doughts and force the user to refer to the previously read information. In the `Wazuh multi-node cluster tab`, it is explained without leaving any doughts. I propose to include this information in both tabs so the user has everything in front of his eyes. There are some small grammar fixes as well.

**Comment by dkempny** [comment]
Pull request: #2250 added for branch: 2250-elastic-cluster-improvement

It contains the improvement of the **Installation guide** - **Elasticsearch cluster section**.

**Comment by jctello** [comment]
I've gone through the installation guide and committed the changes I saw necessary.
Green light from me.

**Comment by jctello** [comment]
I've now done the installation process on a distributed environment with 2 Wazuh nodes, 3 Elasticsearch nodes and both a standalone Kibana and a Kibana on top of an Elasticsearch node.

I've noticed four things to be fixed:
 - [ ] Wazuh API service is not enabled or started
 - [ ] Filebeat configuration assumes a single Elasticsearch node (or point of entry). 
 - [ ] Before installing the Wazuh Kibana plugin one must cd into `/usr/share/kibana/` or it will fail.
 - [ ] The Wazuh Kibana plugin's configuration file `/usr/share/kibana/plugins/wazuh/wazuh.yml` needs to be edited to have the API URL and credentials

**Comment by jctello** [comment]
I would also add `filebeat test config` and `filebeat test output` to the instructions.

**Comment by jctello** [comment]
A couple of additional comments. 
The Wazuh API is not automatically started on some OS. I just verified and Ubuntu Bionic does not exhibit this issue, but Ubuntu Trusty (14.04) does. 

Another room for improvement is to separate the code lines that cannot be simply copy/pasted. For example the certificate distribution instructions will not run, hence making the "Copy to clipboard" button fail.

**Comment by davidfmiranda** [comment]
Hello team!

We are going to include several modification to the new installation guide structure:

- Split between all-in-one installation and **distributed** installation.
- Add minimum requirements to the all-in-one section.
- Add a minimum requirements section in distributed installation.
- Modify the actual installation process:
  - Use Open Distro for Elastic Stack installation.
  - Add an "Unsupported Installation" section top explain how to install Elastic Stack using scripts.

Regards,

David

**Comment by alberpilot** [comment]
I proceed to close this one, the requirements were modified. Now: https://github.com/wazuh/wazuh-documentation/issues/2900
