### ISSUE TITLE
New installation guide deployment

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#2900]
A new installation guide is currently under development. 

Branch: https://github.com/wazuh/wazuh-documentation/tree/2205-Open_Distro_installation

### New installation guide main tasks

- [ ] Finishing the last review iteration (global). 
  - [ ] Last review iteration over Step by step guides (@s-ocando). In progress.
  - [ ] Last review iteration over Unnatended guides (@s-ocando). In progress.
- [ ] @alberpilot/@snaow validation.
- [ ] @santiago-bassett validation. 

### Dependencies for 4.0.0

Before to release it in 4.0.0: 

- [x] 4.0.0 Release notes (#2819).
- [x] Merge 3.13 into this branch. 
- [x] Review versions: all 3.x references must be checked. New packages repositories will be under the 4.x folder. 
- [x] Package list update with new Open Distro for elasticsearch and elasticsearch/filebeat/kibana packages path, links, and checksums. 
- [x] Check redirections. 
- [x] Review the clean installations about the new `not automatically start` of the service. 
- [x] Review new 4.x elasticsearch index renaming. 
- [x] Check changes in branch `new-documentation-structure`.
- [x] Check the `Elasticsearch tuning` section.
- [x] OVA rework with Open Distro for elasticsearch: https://github.com/wazuh/wazuh-documentation/issues/2662.
- [x] MSU download link and checksum in package list: https://github.com/wazuh/wazuh-documentation/issues/2906
- [x] Wazuh kibana plugin users and roles: https://github.com/wazuh/wazuh-documentation/issues/2965
- [x] Remove Wazuh manager 32 bits references: https://github.com/wazuh/wazuh-documentation/issues/2977
