### ISSUE TITLE
Documentation for unlimited agents epic

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-documentation#2991]
Review Wazuh documentation to see if it is necessary to introduce some changes related to the unlimited agents epic:

- [x] Review rootcheck documentation.

- [x] Review RIDS documentation.

- [x] Review remote upgrading documentation.

- [x] Review remoted documentation.

- [x] Review any file that will reference the number of MAX_AGENTS allowed to register to a single manager.
