### ISSUE TITLE
Installation guide improvements

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3588]
Hello team!

The aim of this issue is to improve the actual installation guide. This implies the following changes:

- [ ] Improve and ease the installation steps.  Scripting all the installation steps that may be confusing or tedious for users.
- [x] Reduce steps during the installation/configuration process.
- [x] Improve the wording and explanations of the installation guide.
- [ ] Improve consistency between the Getting started section and the installation guide.
- [x] Reorganize the installation guide.
- [x] Scripts and configuration templates should be hosted on `wazuh-packages`.
- [ ] Improve the unattended installation script #3364.
- [x] Include the certificate tool #3128 

Regards,

David

**Comment by MarVergara** [comment]
**IG Review_ **

- [ ] Installation guide index
  - [ ] Requirements
  - [ ] Wazuh server
    - [ ] All-in-one deployment
      - [ ] Unattended installation
      - [ ] Step-by-step installation
    - [ ] Distributed deployment 
      - [ ] Unattended installation
        - [ ] Elasticsearch & Kibana unattended installation 
        - [ ] Wazuh server unattended installation
      - [ ] Step-by-step installation
        - [ ] Elasticsearch cluster
          - [ ] Elasticsearch single-node cluster 
          - [ ] Elasticsearch multi-node cluster
        - [ ] Wazuh cluster 
          - [ ] Wazuh single-node cluster
          - [ ] Wazuh multi-node cluster
          - [ ] Kibana
  - [ ] Wazuh agent 
    - [ ] AIX 
    - [ ] HP-UX
    - [ ] Linux
    - [ ] macOS
    - [ ] Solaris
    - [ ] Windows
    - [ ] Deployment variables
      - [ ] Deployment variables for AIX
      - [ ] Deployment variables for Linux
        - [ ] Deployment variables for Linux using apt repository
        - [ ] Deployment variables for Linux using dnf repository
        - [ ] Deployment variables for Linux using yum repository
        - [ ] Deployment variables for Linux using zypper repository
      - [ ] Deployment variables for macOS
      - [ ] Deployment variables for Windows
  - [ ] Packages list 
  - [ ] More installation alternatives
    - [ ] Wazuh with Elastic Stack basic license
      - [ ] All-in-one deployment
        - [ ] Unattended installation
        - [ ] Step-by-step installation
      - [ ] Distributed deployment 
        - [ ] Unattended installation
          - [ ] Elasticsearch & Kibana unattended installation 
          - [ ] Wazuh server unattended installation
        - [ ] Step-by-step installation
          - [ ] Elasticsearch cluster
            - [ ] Elasticsearch single-node cluster 
            - [ ] Elasticsearch multi-node cluster
          - [ ] Wazuh cluster 
            - [ ] Wazuh single-node cluster
            - [ ] Wazuh multi-node cluster
          - [ ] Kibana
    - [ ] Wazuh with Splunk
      - [ ] Install Splunk in single-instance mode
      - [ ] Installing & Configuring Splunk Cluster
      - [ ] Install the Wazuh app for Splunk
      - [ ] Install and configure Splunk Forwarder
      - [ ] Setting up reverse proxy configuration for Splunk
      - [ ] Customize agents status indexation
    - [ ] Wazuh installation from sources 
      - [ ] Installing Wazuh server from sources 
      - [ ] Installing Wazuh agent from sources
