### ISSUE TITLE
Adapt Getting Started section for Wazuh 5.0

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3694]
Hello team! The aim of this issue is to adapt the Getting started section to include the incoming changes:

- [ ] Improve the wording of the section.
- [ ] Adapt the Getting started index.
- [ ] Adapt the Components section.
- [ ] Adapt the Architecture section.
- [ ] Adapt the Use cases section.
- [ ] Updated the existing diagrams.
- [ ] Define the nomenclature to be used.

Regards,

David

**Comment by s-ocando** [comment]
A new Getting Started section that describes the new Wazuh components was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
