### ISSUE TITLE
5.0 Installation guide rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3697]
Hello team!

The aim of this issue is to adapt and improve the installation guide for Wazuh 5.0. This implies the following changes:

- [ ] Adapt the installation steps to the new packages.
- [ ] Adapt the nomenclature used. 
- [ ] Reorganize the menu #3588.
- [ ] Reduce and ease the installation process.
- [ ] Adapt the configuration templates.
- [ ] Adapt the unattended installation script with its incoming upgrades #3364.
- [ ] Adapt the diagrams to match the new packages.

The structure of the menu will be the following:

- Quickstart
- Central components
    - Wazuh indexer
    - Wazuh manager
    - Wazuh WUI
- Wazuh agent
- Package list

**Comment by MarVergara** [comment]
This issue is no longer structured according to our roadmap.
