### ISSUE TITLE
Current Installation guide rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3865]
Hello team!

The aim of this issue is to improve and reorganize the current installation guide.

We must ease the installation process by reorganizing the different installation and deployment alternatives to follow this menu:

**Edit:** The menú has been changed. This is the menu V2:

<img width="779" alt="New_documentation_structure_v2" src="https://user-images.githubusercontent.com/60152567/124584909-0ad13000-de55-11eb-8db3-2f31afe01a27.png">

<details>
  <summary>Menu V1</summary>
 
![image](https://user-images.githubusercontent.com/60152567/119863846-4d305480-bf1a-11eb-9a67-09eccbbca05a.png)
</details>

Besides, the content of each section must be adapted to the new structure and simplify the steps where possible.

The sections to simplify are:

- [x] Installation guide index #3857
- [x] Quickstart #3858
- [x] Step-by-step installation #3859
- [x] Unattended installation #3860
- [x] Wazuh agent #3861
- [x] Package list
- [x] More installation alternatives #3863

This issue is related to #3364 since the unattended scripts improvements must be ready before this issue can be merged.

Regards,

David
