### ISSUE TITLE
Writing highlights for Wazuh 4.2.2 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4326]
Hi team,
This issue aims to create highlights for Wazuh 4.2.2 release notes. 

Tasks:

- [x] Create a Drive doc to write the highlights: [Writing highlights for Wazuh 4.2.2 release notes](https://docs.google.com/document/d/1UQIxGmEDf00a1UXnwsp-x763VF688F6J56zyOrJ-sMk/edit?usp=sharing)
- [x] Read and create highlights for the following pull requests:
  - [x]  [Issue 1: Bring Authd the capability to avoid re-registering agents that already has valid keys · Pull Request #9779](https://github.com/wazuh/wazuh/pull/9779)
  - [x] [Issue 2: Rework GCP Pub/Sub integration · Pull Request #9927](https://github.com/wazuh/wazuh/pull/9927)
  - [x] [Issue 3: Move API selector and Index Pattern Selector to the header bar · Pull Request #3175](https://github.com/wazuh/wazuh-kibana-app/pull/3175)
  - [x] [Issue 4: New functionality to change app logos · Pull Request #3503](https://github.com/wazuh/wazuh-kibana-app/pull/3503)
  - [x] [Issue 5: Add quick settings view · Pull Request #1107](https://github.com/wazuh/wazuh-splunk/pull/1107)

- [x] Final editorial review with @MarVergara 

Regards,
Damian

**Comment by Arcapas** [comment]
PR #9779 highlight:
Authd now refuses enrollment attempts if the agent already holds a valid key. Since the introduction of Enrollment in Wazuh 4.0.0, the agents execute the registration process automatically, without user intervention. Till now, this has caused agents to massively self-register under certain circumstances, even if they are already registered. With this added feature, Authd can only generate new keys if the agent key doesn't exist on the manager side. Based on this, the manager will have the capability to decide if a new key should be generated or not.

**Comment by Arcapas** [comment]
Issue 2 highlight
The Google Cloud Pub/Sub integration module was updated to increase processed events per second. The rework of this integration module allows multithreading, increases performance significantly, and adds a new num_threads option to the module configuration. The new multithreading feature allows pulling messages with multiple subscribers simultaneously, improving the performance drastically. In addition, this new gcloud integration included some improvements in the pulling and acknowledging mechanism and the socket connection.

**Comment by Arcapas** [comment]
**Issue 3 highlight**
Wazuh improves the API selector and Index Pattern Selector of the Wazuh Kibana plugin moving both from the Menu to the upper right corner of the header bar. This new UX improvement will allow users to have a better management of this two elements. First, users will be able to see the API selector when there is more than one to select. Second, user will see the Index Pattern Selector when there is more than one to select and only will see the index patterns that have Wazuh alerts.

**Comment by Arcapas** [comment]
**Issue 4 highlight**
Wazuh adds a new functionality that enables changing the logotypes of the Wazuh Kibana plugin. Now users can customize the logos of this app easily. They only need to go to Settings, Configuration, Logo Customization, and define the name to the app logo, logo sidebar, and health check. Finally, add the new logos in the /usr/share/kibana/plugins/wazuh/public/assets path inside the Kibana container, then change the name and save.

**Comment by Arcapas** [comment]
**Issue 5 highlight**
Wazuh added Quick Settings to improve the view and selection of API, index, and source type of the Wazuh Splunk app. Now users can change the configuration of these elements easily from the new Quick Settings menu in the app.
