### ISSUE TITLE
Writing components descriptions for the product page

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4394]
Hi team,
This issue aims to create components descriptions for the product page.

### Tasks:

- [x] Create a Drive doc to write the components descriptions: [Components description for the product page V1.0](https://docs.google.com/document/d/1AAYmRJ1AXPBDDzGE2Q61hv-54tFaf2PVpF2AnU5X7XM/edit?usp=sharing)
- [x] Read the components and Installation guide pages from the documentation section.
- [x] Then write components descriptions for the product page.
- [x] Final editorial review with @MarVergara 

Regards,
Damian

**Comment by Arcapas** [comment]
### Components descriptions

**Wazuh agent**
The Wazuh agent is a multi-platform component that runs on the hosts that the user wants to monitor. It provides prevention, detection, and response capabilities.

**Wazuh server**
This central component is used to manage the agents, configuring and upgrading them remotely when necessary. It analyzes data received from the agents, processing it through decoders, rules and using threat intelligence to look for indicators of compromise.

**Wazuh indexer**
This component indexes and stores alerts generated by the Wazuh server. It is a highly scalable, full-text search and analytics engine. It can be installed as a single-node or multi-node cluster depending on the environment needs.

**Wazuh dashboard**
The Wazuh dashboard is a flexible and intuitive web interface for mining, analyzing, and visualizing data. It is used to manage Wazuh configuration and to monitor its status.

**Comment by PilarQuesada** [comment]
I have reviewed the texts and proposed some minor changes: 

**Wazuh agent**
The Wazuh agent is a multi-platform component that runs on the hosts to be monitored. It provides prevention, detection, and response capabilities.
**Wazuh server**
The server manages the agents, configuring and updating them remotely when necessary. This component analyzes the data received from the agents, processing it through decoders and rules, and using threat intelligence to look for indicators of compromise.
**Wazuh indexer**
The Wazuh indexer is a highly scalable full-text search and analysis engine. It is responsible for indexing and storing alerts generated by the Wazuh server. It can be installed as a single-node or multi-node cluster, depending on the environment needs.
**Wazuh dashboard**
A flexible and intuitive web interface for data mining, analysis and visualization. The dashboard is used to manage the Wazuh configuration and monitor its status.
