### ISSUE TITLE
Create Release Notes for Release 4.3.0

### ISSUE THREAD

**Issue by MarVergara** [wazuh/wazuh-documentation#4588]
Hi team,
This issue aims to create the Release Notes for 4.3.0 that will be published on the GA date.
The commits of this issue can be seen here: https://github.com/wazuh/wazuh-documentation/commits/4.3-rc

### Stage 1:
- [x] Create branch and template
- [x] Check Changelogs and add issues from `wazuh/wazuh rc1`:
    -  Highlights
        - [x] Manager
        - [x] Agent
        - [x] Wazuh Kibana plugin
        - [x] RESTful API
    -  What’s new
        - [x] Manager
        - [x] Agent
        - [x] RESTful API
        - [x] Ruleset
        - [x] Wazuh Kibana plugin
        - [x] Others
    -  Resolved issues
        - [x] Manager
        - [x] Agent
        - [x] RESTful API
        - [x] Ruleset
        - [x] Wazuh Kibana plugin
        - [x] Others
   - [x] Changelogs
- [x] Edit the content and check that the new added issues are consistent
- [x] Check correspondence between issue number and number in link
- [x] Make necessary linguistic adjustments
- [x] Check Changelogs and add issues from `wazuh/wazuh rc2`
- [x] Check Changelogs and add issues from `wazuh-kibana-app/CHANGELOG.md`
- [x] Check Changelogs and add issues from `wazuh-splunk/CHANGELOG.md`
- [x] Check Changelogs and add issues from `wazuh/wazuh rc3`
- [x] Check Changelogs and add issues from `wazuh/wazuh rc4`
- [x] Check Changelogs and add issues from `wazuh/wazuh rc5`
- [x]  Check Changelogs and add issues from `wazuh/wazuh rc6`
- [x]  Check Changelogs and add issues from `wazuh/wazuh rc7`
- [x] Check Changelogs and add issues from `wazuh-packages/CHANGELOG.md`
- [x] Edit the content and check that the new added issues are consistent
- [x] Check correspondence between issue number and number in link
- [x] Make necessary linguistic adjustments
- [x] Review from the content team

### Stage 2:
- [x] Work on the branch `4.3.0-release-notes-update`
- [x] Make a review, add updates and make fixes
- [x] Review from the content team

Further steps will be added if additional revisions are needed for new release candidates.

Regards,
Mariel and Damián
