### ISSUE TITLE
New installation guide rework publishing: acceptance criteria and action items

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#4642]
This issue aims to define what makes the new installation guide able to be published. 

### Teams involved

- @wazuh/content: this team elaborates the guide, schema, pages hierarchy, etc. All redaction is on his own.
- @wazuh/cicd: this team (specifically the installer team) must deliver the called Unattended installer. This installer allows the user to simplify the Wazuh deployment. All technical-related issues (installer development, resources placing on public URLs, automated testing, etc) must be done by his team. 

### Validation

- @agusofa from @wazuh/content ensuring the Content team criteria.
- @alberpilot from @wazuh/cicd ensuring the Installer team development and infrastructure criteria. 
- @havidarou, @jctello, and @orsifacundo from @wazuh/operations ensuring the usability and customer/users focus mindset. 
- Additionally, @santiago-bassett could provide feedback. 

# Content team tasks:
- [ ] Identify long URLs and ask the installer team for the new proposal. https://github.com/wazuh/wazuh-packages/issues/1047
- [ ] https://github.com/wazuh/wazuh-documentation/issues/3860
- [ ] https://github.com/wazuh/wazuh-documentation/issues/4702
<details><summary><strong>Content team acceptance cirteria</strong></summary>
<be>

<b><i>Documentation testing</i></b><be>

- Testing installation steps of each section.
   - Report to CICD if the process does not work.
   - Detect possible improvements.
   - Report to CICD of required changes if needed.
   - Improve documentation if needed according to results from the previous task.
   - All tests against the IG steps are passed (full green).

<b><i>Information structure</i></b><be>

- The section follows a planned and logical organization.
- The section has a meta description (between 120 and 150 characters).
- The H1 title is descriptive (50 and 70 characters).
- The introduction must anticipate the contents of the section.
- The section has a Prerequisite subsection - if needed
- The title of tasks is descriptive (50 and 70 characters).
- The short description anticipates the goal of the task - if needed
- Tasks have a maximum of 9 (numbered) steps - recommended 
   - Add result sentences for complex tasks. 
- All lists have grammatical and syntactic parallelism. 
- The section has a Next Steps entry if needed. This entry should have more than one sentence. 

<b><i>Editorial </i></b><be>

- Run the text through Grammarly.
   - Fix detected errors.
- Sentences are simple structures and to the point. 
   - Break down complex sentences into simpler ones if needed.
- Sentences in tasks are simple and tell the user what to do. The use of the imperative is recommended.
- All sentences have a conjugated verb when necessary. 
- All code blocks are well structured.
- All tables are well structured.
- Titles are formatted correctly [H1, H2, H3]
- The text contains impersonal speech.
- The text contains uppercase only on nouns.
- Run the text through Grammarly for final check.
- Peer review.

<b><i>Final checks</i></b><be>

- Add redirects for new sections if needed.
- All redirects work.
- All URLs work.
- The text reads correctly.
- The branch compiles without errors.

</details>

</details>

# Installers team tasks
### To-Do:
- [x] https://github.com/wazuh/wazuh-packages/issues/848
- [x] https://github.com/wazuh/wazuh-packages/issues/854 Assigned @rauldpm 
- [x] https://github.com/wazuh/wazuh-packages/issues/943 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/1062 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/1071 Assigned @verdx
- [x] https://github.com/wazuh/wazuh-packages/issues/1063 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/1045 Assigned @DFolchA 
- [x] https://github.com/wazuh/wazuh-packages/issues/1102 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/952 Assigned @rauldpm 
- [x] https://github.com/wazuh/wazuh-packages/issues/967
- [x] https://github.com/wazuh/wazuh-packages/issues/1109 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/865 Assigned @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/1057 Assigned @DFolchA 
- [x] https://github.com/wazuh/wazuh-packages/issues/1120
- [x] https://github.com/wazuh/wazuh-packages/issues/1036 Assigned @rauldpm and @lastranikos 
- [ ] https://github.com/wazuh/wazuh-packages/issues/1047 Assigned @teddytpc1 
- [ ] https://github.com/wazuh/wazuh-packages/issues/867 (first iteration) Assigned @DFolchA and waiting for # 1045 and # 1057 
- [ ] https://github.com/wazuh/wazuh-documentation/issues/4766
- [ ] https://github.com/wazuh/wazuh-jenkins/issues/3253
- [ ] Change API default password. 

### Tentative:
- [ ] https://github.com/wazuh/wazuh-packages/issues/1205
- [ ] Choose the component to uninstall.
- [ ] Deploy agents into the Elasticsearch/Kibana nodes
- [ ] https://github.com/wazuh/wazuh-packages/issues/847
- [ ] https://github.com/wazuh/wazuh-packages/issues/863
- [ ] https://github.com/wazuh/wazuh-packages/issues/862
- [ ] https://github.com/wazuh/wazuh-packages/issues/968

<details><summary><strong>Installer team acceptance cirteria</strong></summary>
<br>

  - All-In-One deployment:
    - [ ] The unattended installer must be able to install an AIO deployment (Wazuh manager + Opendistro for Elasticsearch + filebeat OSS + Opendistro for Kibana).
    - [ ] After running the unattended installer the user must be able to connect Wazuh agents to the Wazuh manager and start seeing alerts on the Wazuh Kibana plugin. 

  - Distributed deployment:
    - [ ] The unattended installer must be able to install only the Wazuh manager and filebeat OSS component.
    - [ ] The unattended installer must be able to create the whole infrastructure certificates (all elasticsearch - filebeat - kibana communications), previously specification file given, no matter the host where the certificates are created. 
    - [ ] If the create certificate option is not activated, the unattended installer must stop 

  - Common (AIO & distributed)
    - [ ] All action steps must be logged in the standard output. All steps must show the timestamp, message type (info, error, warning), and the step description. This output must be written in the log file too, located at `/var/log/wazuh-unattended-installation.log`
    - [ ] If the debug flag is activated, all commands (commands and output) must be logged in standard output and debug file.
    - [ ] A random password must be generated during the installation, avoiding the default one. This new random password must be shown in the installation process output. 
    - [ ] If a component installation fails, the installer must roll back the installation, cleaning all installed components and their folders. The rollback must be logged too. 
    - [ ] Every function invocation must manage the possible error and if it occurs, an exit with a rollback (if necessary). Example: <i>importFunction "common.sh"</i> could be <i>importFunction "common.sh" || (logger -e "It was not possible to import common.sh library. Exiting" && exit 1)</i>
    - [ ] The unattended installer must not be running indefinitely. All necessary steps must be controlled by timeouts. 
    - [ ] The unattended installer must check if all needed resources are available (on-line and off-line) before starting installing/configuring actions. 
  

</details>
