### ISSUE TITLE
Enhance the Installation guide and Wazuh quickstart sections V1.0

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4655]
This issue aims to enhance the Installation guide and Wazuh quickstart sections.

### Tasks
- [x] Create a branch: `4655_3865_installation_guide_and_quickstart_enhanced`
- [x] Chang and improve the way content is explained and written.
- [x] Simplifying the language used and easing the explanations where possible.
- [x] Make a last review of the text
- [x] Make PR: #4658

Regards,
Damian Furfuro
