### ISSUE TITLE
Enhance the Installation guide and Wazuh quickstart sections V2.0

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4659]
This issue aims to enhance the Installation guide and Wazuh quickstart sections.

### Tasks - QUICKSTART
- [x] Change and improve the way content is explained and written.
- [x] Simplifying the language used and easing the explanations where possible.
- [x] Create a branch: `4660_3865_installation_guide_and_quickstart_enhanced_v2.0`
- [x] Edit the text fixing the text errors
- [ ] Make a last review of the text

### Tasks - IG - index
- [x] Change and improve the way content is explained and written.
- [x] Simplifying the language used and easing the explanations where possible.
- [x] Create a branch: `4660_3865_installation_guide_and_quickstart_enhanced_v2.0`
- [x] Edit the text fixing the text errors
- [x] Make a last review of the text
- [x] Make PR and ask the content team for review

Regards,
Mariel
