### ISSUE TITLE
Enhance the Getting started, Installation guide and Wazuh quickstart sections V5.0

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4681]
This issue aims to enhance the Installation guide and Wazuh quickstart sections.

##  Tasks
- [x] Create a branch: `4681_3865_installation_guide_and_quickstart_enhanced_v5.0`
- [x] Make changes and improvements following the point shared with the content team
- [x] Create a new structure for the **Getting started** section:
   - Intro
   - Community and support
   - How to install Wazuh      
   - Wazuh Cloud
   - Useful resources
   - Table of contents
- [x] Make a last review of the text
- [x] Make PR: #4686
- [x] Make PR: #4691 
- [x] Make PR: #4692
- [x] Make PR: #4694
- [x] Make PR: #4695
- [x] Make PR: #4696

Regards,
Mariel, Javier and Damian
