### ISSUE TITLE
Rework the section: Installation alternatives 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4717]
This issue aims to enhance the section **Installation alternatives** 

##  Tasks
- [x] Create a different menu items distribution according to the points discussed with the content-team
- [x] Create a branch: `4717_3865_installation_alternatives_rework_v1`
- [x] Make a PR: #4718
- [x] The new  **Installation alternatives** menu contains the following items:
    - Ready-to-use machines
    - Containers options
    - Offline installation
    - Installation from sources
    - Commercial options
    - Orchestration tools
- [x] Editing the following sections of the index page:
    - Containers
    - Commercial options
    - Orchestration tools
- [x] Create an alternative branch for merging: `4717_3865_installation_alternatives_rework_v2`
- [x] Merge with `3865_installation_guide_rework`
- [x] Make a PR: #4726
- [x] Make a last review

**Comparing both versions of the Installation alternatives menu:**
![Rework the section: Installation alternatives · Issue #4717](https://user-images.githubusercontent.com/85168963/148227347-e5e6d33e-f22e-49ca-8664-3bf68561f01d.png)

Regards,
Damian Furfuro
