### ISSUE TITLE
Documentation enhancement works v1.0

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4734]
This issue aims to enhance the menu and different sections of the documentation.

##  Tasks
- [x] I create the branch `4717_3865_installation_alternatives_rework_v3`
- [x] Make the PR #4735
- [x] I create the branch `4734_documentation_enhancement_works_1`
- [x] Make the PR #4801

##  Iteration 1 (01/12/2022)
- [x] Make changes and improvements following the points shared with the content team:
    - [x] Change the `industry-leading` of the GS.
    - [x] Put a drop-down menu in `container-options`
    - [x] Use the `admonition` function for the Cloud warning without the exclamation mark
    - [x] Change `Commercial options` and place the two items in the menu
    - [x] Unify the sections within `Installation from sources`
    - [x] Test to replace the tabs with a list inside the section `Installing Wazuh agent from sources`
- [x] Make a last review of the changes and files
- [x] Share it with the content team

##  Iteration 2 (01/13/2022)
- [x] Make changes and improvements following the points shared with the content team:
    - [x] Write a short description for `Installing Wazuh agent from sources`
    - [x] Add the Linux tabs to the section `Installing Wazuh agent from sources`
    - [x] Quit `Installing` from the menus of:
        - [x] Installing Wazuh with Elastic Stack basic license
        - [x] Installing Wazuh with Splunk
- [x] Share it with the content team

##  Iteration 3 (01/14/2022)
- [x] Make changes and improvements following the points shared with the content team:
    - [x] Improve the short description for `Installing Wazuh agent from sources`
    - [x] Delete: `Note: Since Wazuh 3.5 it is necessary to have internet connection when following this process.`
    - [x] Create at startup: `Note: All commands described below must be executed with root privileges.` Place after: _The Wazuh manager and agent can be installed via sources as an alternative to the installation from packages._
    - [x] Ask CICD to change the place of the `Note: CMake 3.12.4 is the minimum library version required to build the Wazuh server solution.   `after: _CMake 3.18 installation
    - [x] Delete the `Note: CMake 3.12.4 is the minimum library version required to build the Wazuh server solution.   `after: _CMake 3.18 installation_ 
    - [x] I change the `Orchestration tools section` to `empty node`
    - [x] Dev version of this changes: [Installation alternatives](https://documentation-dev.wazuh.com/4717_3865_installation_alternatives_rework_v3/deployment-options/index.html
)

##  Iteration 4 (01/18/2022)
- [x] I create some Google docs with the improvement works of the following section of the documentation:
    - [x] Getting started
    - [x] Quickstart
    - [x] Installation guide
    - [x] Installation alternatives
- [x] I work on the enhancement of the `Installation alternatives`

##  Iteration 5 (01/24/2022)
- [x] I update the Google docs below according with each branches:
    - Branch: `3865_installation_guide_rework`
         - Doc: `Getting started v1.0`
         - Doc: `Quickstart v1.0`
         - Doc: `Installation guide v1.0`
    - Branch: `3865_installation_alternatives_rework_v3`
         - Doc: `Installation alternatives v1.0`

##  Iteration 6 (01/26/2022)
- [x] I'm completing all the pages of the following sections in each doc below:
    - [x] Doc: `Getting started v1.0`
    - [x] Doc: `Quickstart v1.0`
    - [x] Doc: `Installation guide v1.0`
    - [x] Doc: `Installation alternatives v1.0`
    - [x] Doc: `Installation alternatives - Virtual Machine (OVA)`
    - [x] Doc: `Installation alternatives - Amazon Machine Images (AMI)`
    - [x] Doc: `Installation alternatives - Deployment on Docker`
    - [x] Doc: `Installation alternatives - Deployment on Kubernetes`
    - [x] Doc: `Installation alternatives - Deployment with Ansible`
    - [x] Doc: `Installation alternatives - Deployment with Puppet`
    - [x] Doc: `Installation alternatives - Offline installation`
    - [x] Doc: `Installation alternatives - Installation from sources`
    - [x] Doc: `Installation alternatives - Installing Wazuh with Elastic Stack`
    - [x] Doc: `Installation alternatives - Installing Wazuh with Splunk`

##  Iteration 7 (02/07/2022)
- [x] Erase AIX 5 from `Upgrade guide > Compatibility matrix` because AIX 5 is no more compatible.

Regards,
Damian Furfuro

**Comment by Arcapas** [comment]
I make some tests with Vagrant and CentOS 6/7/8 for the section  `Installation from sources` but I get some errors trying the following instructions:
```
# yum install make cmake gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel cmake
# rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
```
  - Errors on CentOS 6:
```
[root@centos6b vagrant]# rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
warning: /var/tmp/rpm-tmp.4mwQeP: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
error: Failed dependencies:
        libstdc++-devel = 8.4.1-1.el8 is needed by libstdc++-static-8.4.1-1.el8.x86_64
```
  - Errors on CentOS 7:
```
[root@centos7 vagrant]# rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
warning: /var/tmp/rpm-tmp.zFeQxr: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
error: Failed dependencies:
        libstdc++-devel = 8.4.1-1.el8 is needed by libstdc++-static-8.4.1-1.el8.x86_64
```
 - Errors on CentOS 8:
```
[root@centos8 vagrant]# rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
error: Failed dependencies:
        libstdc++-devel = 8.4.1-1.el8 is needed by libstdc++-static-8.4.1-1.el8.x86_64
```
