### ISSUE TITLE
Wazuh v3.7.0 release documentation

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#475]
Hi team,

For the next Wazuh release, we have to change the documentation:

### Pending:
Update checksums for:
  - [x] Packages list
  - [x] WPKs
  - [x] Apps
  - [x] VMs

### Done:
- [x] ~Release notes (#473 & #502).~ (Merged)
- [x] ~Update all documentation links for Wazuh v.3.7.0 (#478).~ (Merged)
- [x] ~Update all documentation articles for Elastic v6.4.2 (#478).~ (Merged)

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Related PR: https://github.com/wazuh/wazuh-documentation/pull/478

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Done here: #601 

Regards,
Juanjo
