### ISSUE TITLE
Documentation enhancement works II

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4777]
This issue aims to enhance different sections of the documentation.

##  Tasks
- [x] I create the branch `4734_3865_enhancement_work`
- [x] Make the PR #4776

##  Iteration 1 (01/20/2022)
- [x] I create some Google docs with the improvement works of the following section of the documentation:
    - [x] Getting started
    - [x] Quickstart
    - [x] Installation guide
- [x] I work on the enhancement of following section of the documentation:
    - [x] Getting started
    - [x] Quickstart
    - [x] Installation guide

Regards,
Damian Furfuro
