### ISSUE TITLE
Documentation and blogposts publishing	

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4798]
This issue aims to follow all the tasks that include Documentation and blog posts publishing.

##  Tasks 1
- [x] I create the Spreadsheet  `Documentation and blog posts publishing v1.0`.
- [x] Share it with threat-intel-team and content-team
- [x] Prepare the blog post `Detecting known bad actors with Wazuh and AbuseIPDB` to be published on Worpress.
- [x] Share the blog post with content-team.
- [x] Publish the blog post on WordPress.
- [x] Prepare the texts for publishing on Linkedin, Twitter, Slack community channel, Google group, and Reddit.
- [x] Perform an editorial review of the blog post `Integrating ModSecurity WAF with Wazuh`.
- [x] Prepare the blog post `Integrating ModSecurity WAF with Wazuh` to be published on Worpress.
- [x] Review SEO and Readability of this blogpost: `New Wazuh partnership with Apps and Cyber Technologies`
- [x] Perform an editorial review of the blog post `Monitoring Docker Container Logs with Wazuh`.
- [x] Prepare the blog post `Monitoring Docker Container Logs with Wazuh` to be published on Worpress.
- [x] Perform an editorial review of the blog post `Deploying Wazuh agents to windows endpoints with PDQ deploy`.
- [x] Prepare the blog post `Deploying Wazuh agents to windows endpoints with PDQ deploy` to be published on Worpress.
- [x] Perform an editorial review of the blog post `Detecting PwnKit (CVE-2021-4034) with Wazuh`.
- [ ] Prepare the blog post `Detecting PwnKit (CVE-2021-4034) with Wazuh` to be published on Worpress.
- [ ] Write a blog post about `Wazuh 4.3.0 release`.
- [ ] Perform an editorial review of the blog post `Wazuh 4.3.0 release`.
- [ ] Prepare the blog post `Wazuh 4.3.0 release` to be published on Worpress.

##  Tasks 2

#Future tasks

- [ ] Perform an editorial review of the blog post `Improving Fin7 detection with Wazuh Feed`.
- [ ] Prepare the blog post `Improving Fin7 detection with Wazuh Feed` to be published on Worpress.
- [ ] Perform an editorial review of the blog post `Improving APT29 detection with Wazuh Feed`.
- [ ] Prepare the blog post `Improving APT29 detection with Wazuh Feed` to be published on Worpress.

**Comment by Arcapas** [comment]
Issue moved to [wazuh/wazuh-marketing #1557](https://github.com/wazuh/wazuh-marketing/issues/1557) via [**ZenHub**](https://www.zenhub.com/)
