### ISSUE TITLE
4.3.0 images update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4909]
This issue aims to list and edit the images that need to be updated for 4.3.0.
The updated images should have the new rebranding look & feel and the new dashboard name: from "Wazuh Kibana plugin" to "Wazuh dashboard."

#  Tasks:
- [x] Review the following characteristic of the images in this stage:
    - Grey edge
    - Centered
    - Correct size
    - Correct titles

## Stage 1
- [x] Work on the branch `4.3-Images-update`
- [x] Work on the PR #4951
- [x] Review the following sections of the documentation:
    - [x] Getting started with Wazuh
    - [x] Quickstart
- [x] Upload the new images to `4.3-rc`

## Stage 2
- [x] Work on the branch `4.3-images-update-stage-2`
- [x] Work on the PR #5084
- [x] Review the following sections of the documentation:
    - [x] Installation alternatives
    - [x] Upgrade guide
    - [x] Cloud service
    - [x] User manual
- [x] Upload the new images to `4.3-rc`

## Stage 3
- [x] Work on the branch `4.3-images-update-stage-3`
- [x] Work on the PR #5105
- [x] Review the following sections of the documentation:
    - [x] Installation guide
- [x] Upload the new images to `4.3-rc`

## Stage 4
- [x] Review the following sections of the documentation:
    - [x] Cloud security
    - [x] Container security
    - [x] Development
    - [x] Compliance
    - [x] Migrating from OSSEC
    - [x] Learning Wazuh
    - [x] Proof of Concept guide
    - [x] Release note

**Comment by Arcapas** [comment]
Add these three images to **Documentation > Release notes > 4.3.0 Release notes**:
![Management-Configuration](https://user-images.githubusercontent.com/85168963/157448938-b59ccef1-89b9-4fce-9ab5-a3ffb6c42dbe.png)
![Office-365-General](https://user-images.githubusercontent.com/85168963/157448943-26f7196b-421a-4415-a7f9-e81316b30228.png)
![packages-inventory](https://user-images.githubusercontent.com/85168963/157448946-390bfd0d-a267-4854-ba08-c0a181906a58.png)
:

**Comment by Arcapas** [comment]
Add these eight images to **Documentation > Installation guide**:

![1](https://user-images.githubusercontent.com/85168963/164772890-a3bed904-77d5-47d0-a34e-93a789cea47c.png)
![2](https://user-images.githubusercontent.com/85168963/164772893-5c661c82-7f96-4be7-a0b0-834bada12056.png)
![3](https://user-images.githubusercontent.com/85168963/164772894-66552334-c31f-4d4b-9442-1a89db4f9788.png)
![4](https://user-images.githubusercontent.com/85168963/164772896-0593c014-b372-493e-9fa3-08639affbba4.png)
![5](https://user-images.githubusercontent.com/85168963/164772898-bb8337cf-f212-496e-87ac-c8fdb5f6a641.png)
![6](https://user-images.githubusercontent.com/85168963/164772902-8832de09-f29f-4776-9d30-58c653fdc31c.png)
![7](https://user-images.githubusercontent.com/85168963/164772903-403f1f4f-e956-48fd-8283-e048aed92e01.png)
![8](https://user-images.githubusercontent.com/85168963/164772905-a7568259-a3fa-49ec-a638-cad2b4cffb65.png)
