### ISSUE TITLE
4.3.0 texts and grammar review

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4920]
This issue aims to perform a texts and grammar review of 4.3.0 documentation:

# Tasks:

- Perform the following tasks:
    - Review grammar
    - Review texts from the Google doc
    - Resolve Wazuh components names when needed

## Stage 1
- [x] Work on the branch: `4.3.0-grammar-review-1.0`
- [x] Work on the PR #4949
- [x] Review the following sections of the documentation:
    - [x] Getting started with Wazuh
    - [x] Quickstart
    - [x] Installation guide
- [x] Ask content team for review

## Stage 2
- [x] Work on the branch: `4.3.0-grammar-review-2.0`
- [x] Work on the PR #5020 
- [x] Review the following sections of the documentation:
    - [x] Upgrade guide
    - [x] Cloud service
    - [x] User manual
- [x] Ask content team for review

## Stage 3
- [x] Work on the branch: `installation-alternatives-grammar-review`
- [x] Work on the PR #5345
- [x] Review the following sections of the documentation:
    - [x] Installation alternatives / Installing Wazuh with Splunk
- [x] Ask content team for review

## Stage 4
- [x] Work on the branch: `installation-alternatives-grammar-review-v2`
- [x] Work on the PR #5363
- [x] Review the following sections of the documentation:
    - [x] Installation alternatives - Virtual Machine (OVA)
    - [x] Installation alternatives - Amazon Machine Images (AMI)
    - [x] Installation alternatives - Deployment on Docker
    - [x] Installation alternatives - Deployment on Kubernetes 
    - [x] Installation alternatives - Offline installation
    - [x] Installation alternatives - Installation from sources
    - [x] Installation alternatives - Installing Wazuh with Elastic Stack
    - [x] Installation alternatives - Deployment with Ansible 
    - [x] Installation alternatives - Deployment with Puppet
- [x] Ask content team for review
