### ISSUE TITLE
Create Release Notes for Release 4.2.6

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4965]
Hi team,
This issue aims to create the Release Notes for 4.2.6 that will be published on the GA date.

### Tasks:

- [x] Work on the branch `4.2-release-4-2-6` 
- [x] Check Changelogs and add issues from `wazuh/wazuh v4.2.6`:
     -  Resolved issues
        - [x] Manager
     - [x] Changelogs
- [x] Edit the content and check that the new added issues are consistent
- [x] Check correspondence between issue number and number in link
- [x] Approval from stakeholders

Regards,
Damián Furfuro
