### ISSUE TITLE
The indexer/dashboard certs folder should have 500 permissions and certificates 400

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#4977]
The permissions given to `certs` folder (the certificates containing folder) should change to 500, which is more restrictive. Certificates should have 400 (if those certificates are created by the script, the script assigns those permissions. If the users put their own certificates, maybe it could be a good idea to indicate what permissions should have). 

## Tasks
- [x] Change in wazuh-documentation
- [x] https://github.com/wazuh/wazuh-packages/issues/1402
- [x] https://github.com/wazuh/wazuh-ansible/issues/738
- [x] https://github.com/wazuh/wazuh-docker/issues/602
- [x] https://github.com/wazuh/wazuh-kubernetes/issues/232
- [x] https://github.com/wazuh/wazuh-jenkins/issues/3394
- [x] https://github.com/wazuh/wazuh-automation/issues/775
- [x] https://github.com/wazuh/wazuh-puppet/issues/458
