### ISSUE TITLE
Update Configuring GCP credentials documentation

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#4996]
|Component|Installation|Operating system|Issue|
|---|---|---|---|
|Documentation|step by step|CentOS 7|[#12898](https://github.com/wazuh/wazuh/issues/12898)|

## Description

During manual testing at https://github.com/wazuh/wazuh/issues/12898 it was found that the `Configuring GCP credentials` section needs some improvement.

### Show how to add a role to the service account

The documentation lacks an example of how to add the role to the mentioned service account. We should add a new screenshot or maybe some steps explaining how this is done.

### Storage Legacy Bucket Writer role is not available

The documentation states that the user must create a Service Account and assign to it the `Storage Legacy Bucket Writer`. The problem here is that for some unknown reasos this particular role does not always show up in the list of available roles during the creation of the Service Account. A workaround usually consists in the creation of a custom role that inherits from the `Storage Legacy Bucket Writer`. 

<details>

<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/10661307/160606648-71560b42-93f1-4f70-bc50-cfaa8cb55958.png)

</details>
We should investigate why this happens and update the documentation with the easiest way to grant the required permissions, which are the following ones:

![image](https://user-images.githubusercontent.com/10661307/160652262-3bf6899b-d819-4223-90bc-57466c1a28d6.png)

### Tasks
- [x] Update the documentation to show how to create a Service Account
- [x] Investigate the reason why the `Storage Legacy Bucket Writer` is not listed during the creation of the Service Account
- [x] Update the documentation to show the easiest way to grant the required permissions.

**Comment by GGP1** [comment]
## Update

Configured and executed the GCP pub/sub and bucket modules creating a custom role first and then following the documentation. I've taken multiple screenshots and started writing a new sections that explains those steps in detail. I've also made some small corrections in other parts of the documentation because they were outdated.

**Comment by GGP1** [comment]
## Update

I was able to run the GCP modules successfully by following these steps:

1. Creating a project
2. Creating a custom role with permissions to access storage buckets and objects
3. Creating a service account and a private key
4. Creating a topic
5. Creating a subscription

The documentation does not cover the step 2, so I added the instructions. I also included a new image in the `Creating service account` section which was already covered but didn't have an image to compare with.

The `Storage Legacy Bucket Writer` is not shown in the list because it has been replaced with the `Storage Admin` role, which grants both `storage.buckets.*` and `storage.objects.*` permissions. We should consider using that instead in the future

### Logs

<details><summary>GCP pub/sub test</summary>

First window

```console
root@wazuh-master:/# /var/ossec/wodles/gcloud/gcloud --integration_type pubsub -p wazuh-dev-407318 -s wazuh-dev-123456-sub -c /var/ossec/wodles/gcloud/credentials.json -l 2    
:gcloud_wodle: - DEBUG - Setting 1 thread to pull 100 messages in total
:gcloud_wodle: - DEBUG - Processing event: {"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 0}
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 0}'"
:gcloud_wodle: - DEBUG - Processing event: {"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 1}
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 1}'"
:gcloud_wodle: - DEBUG - Processing event: {"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 2}
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": [Wed Dec  6 19:12:36 2023] - Framework publish message 2}'"
:gcloud_wodle: - INFO - Received and acknowledged 3 messages
```

Second window

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 gcp_publisher.py 3  
Message published: 9095960687721396
Message published: 9096283920653459
Message published: 9096257323910369
```

</details>

<details><summary>GCP bucket test</summary>

```console
root@wazuh-master:/# /var/ossec/wodles/gcloud/gcloud --integration_type access_logs -b framework-test-bucket -c /var/ossec/wodles/gcloud/credentials.json --prefix test_prefix --only_logs_after '2021-Jan-01' -l 2
:gcloud_wodle: - INFO: The creation time of test_prefix/test_1.txt is older than 2022-01-01 00:00:00+00:00. Skipping it...
:gcloud_wodle: - INFO: Skipping previously processed file: test_prefix/test_2.txt
:gcloud_wodle: - INFO: Received 0 messages
:gcloud_wodle: - DEBUG: Fetching logs finished.
```

</details>

**Comment by GGP1** [comment]
## Update

- Applied a grammar improvement suggestion
- Highlighted "Create Role" form fields

**Comment by GGP1** [comment]
## Update

Applied the changes suggested in the code review.
