### ISSUE TITLE
Wazuh deployment with Puppet documentation outdated according to the testing done for Wazuh 4.3 RC5

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-documentation#4997]
### Description

This issue summarizes some inconsistencies and errors in the **Wazuh deployment with Puppet** documentation. These things were found during the testing done for Wazuh 4.3 RC5 (https://github.com/wazuh/wazuh/issues/12877):

- [x] The creation of the symbolic link to the Puppet binaries with the command `ln -s /opt/puppetlabs/bin/puppet /bin` is only suggested for Debian/Ubuntu. It should also be mentioned in the installation instructions for Centos.
- [x] In the certificates setup, the guide suggests using the command `puppet cert list`. This command is no longer available in Puppet 6 and should be suggested the usage of `puppetserver ca list`.
- [x] There is a **warning** indicating that for Debian-based systems, the `repo.pp` file should be edited with the `apt::key`. This is already in this file for the Wazuh Puppet plugin in version **4.3**.
- [x] The example of a manifest **wazuh-manager.pp** generates the next error for `wazuh::activeresponse` and should be replaced with a working example:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Wazuh::Activeresponse[blockWebattack]:
has no parameter named 'command_name'
has no parameter named 'ar_level'
has no parameter named 'ar_agent_id'
has no parameter named 'ar_rules_id'
has no parameter named 'ar_repeated_offenders'
```

- [x] The variables `log_name` and `agent_log` cause the next error when they are used in both, manager and agent `wazuh::addlog` function. They seem to be deprecated. This should be confirmed and they should be removed if so.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Wazuh::Addlog[monitorLogFile]:
has no parameter named 'log_name'
has no parameter named 'agent_log' (file: /etc/puppetlabs/code/environments/production/manifests/wazuh-master.pp, line: 60) on node localhost.localdomain
```

- [x] The variable `ossec_service_provider` causes errors in puppet. If it is deprecated, it should be removed from the documentation.
- [x] The variable `active_response_repeated_offenders` for the function `wazuh::activeresponse` of Wazuh manager is used in the examples as a string of comma-separated values (like `"30,60,120"`). This is not correct as it should be an array of values like `[30,60,120]`. This should be better explained and the examples should be fixed as it generated the next error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template wazuh/fragments/_activeresponse.erb:
Filepath: /etc/puppetlabs/code/environments/production/modules/wazuh/templates/fragments/_activeresponse.erb
Line: 37
Detail: undefined method `join' for "30,60,120":String
(file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/activeresponse.pp, line: 27, column: 16) (file: /etc/puppetlabs/code/environments/production/manifests/wazuh-master.pp, line: 52) on node localhost.localdomain
```

- [ ] There aren't instructions explaining how to deploy the Wazuh indexer.

- [ ] The instructions to install the proper puppet version should be updated. They suggest for Debian-based OS to install the `https://apt.puppetlabs.com/puppet5-release-xenial.deb` repository. But this version doesn't exist for focal. If we use [puppet-release-focal.deb](https://apt.puppetlabs.com/puppet-release-focal.deb) or [puppet6-release-focal.deb](https://apt.puppetlabs.com/puppet6-release-focal.deb) instead, the command `apt-get install -y puppetserver` without specifying any version could end up installing the version 7 (it isn't supported by the Wazuh puppet module).

- [ ] Considering this comment https://github.com/wazuh/wazuh-puppet/issues/459#issuecomment-1087660989, the `ossec_local_files` (params_manager.pp/params_agent.pp) variable has to be set in the **correct** case statement in order to work properly. The whole process of `localfiles` should be described in more detail 

- [x] The following settings don't work for the Manager class. They should be confirmed and removed accordingly
```
ossec_auth_force_insert
ossec_auth_force_time
ossec_rootcheck_windows_disabled
ossec_rootcheck_windows_windows_apps
ossec_rootcheck_windows_windows_malware 
```

- [x] The `ossec_emailnotification` variable isn't properly described. The module expects a Boolean (true/false), but the documentation describes it like a String (yes/no)

- [ ] Any email related setting will work if ` ossec_emailnotification` isn't set (see https://github.com/wazuh/wazuh-puppet/issues/459#issuecomment-1087698858). This should be properly described.

- [x] The `ossec_local_files` variable is named but it can't be used. To configure the **localfiles** section it names the `params_manager.pp/params_agent.pp` but this isn't properly described in the documentation. Also, the changes in these files are only detected by the Ubuntu puppet agent and not the CentOS agent

- [x] The `ossec_auth_ssl_manager_cert` has an incorrect default value in the documentation (yes)

- [x] The `ossec_auth_ssl_manager_key` has an incorrect default value in the documentation (yes)

- [ ] The `ossec_remote_connection` variable can't be set to **syslog** because the default value of `queue_size` generates a configuration error. A warning about this should be added (see comment https://github.com/wazuh/wazuh-puppet/issues/459#issuecomment-1087690192)

- [ ] The following variables report an error for the Agent class. Some of them shouldn't be able for Wazuh agents. They should be confirmed and removed accordingly (for config profiles see https://github.com/wazuh/wazuh-puppet/issues/459#issuecomment-1087811996)

```
active_response_disabled
active_response_ca_verification
active_response_location
active_response_level
active_response_agent_id
active_response_rules_id
active_response_timeout
active_response_repeated_offenders
ossec_config_profiles
``` 

- [x] The variable `wazuh_register_endpoint` must be defined but it isn't written in the **ossec.conf** file, so it isn't clear where/how it's used

- [ ] The variable `configure_active_response` when is activated in the agent class, tries to read the **params_manager.pp** file. It should be confirmed if it really corresponds to the agents. Also, the documentation has a description related to **rootcheck** instead of **active_response**

- [ ] The variable `configure_rootcheck` doesn't correspond to any Wazuh variable and it should be explained properly

- [x] Any enrollment variable will work if `wazuh_enrollment_enabled` isn't set (see https://github.com/wazuh/wazuh-puppet/issues/459#issuecomment-1087822031). This should be explained more in detail.

- [ ] The PuppetDB section has to be updated because the current steps don't work

- [x] The variable `configure_sca` is duplicate 

- [x] The variable `vulnerability_detector_provider_debian_os` shows Ubuntu flavors

- [x] The following `sca` variables have no effect on agent class.
```
sca_rhel_enabled
sca_rhel_scan_on_start
sca_rhel_interval
sca_rhel_skip_nfs
sca_rhel_policies
```

- [ ] There's no information for Windows, ALAS Linux y Arch Linux providers in the Vulnerability Detector module.

- [ ] The explanation of the `manage_client_keys` variable is not clear. We were not able to understand the use case for that variable.

- [ ] The following variables don't exist in the manager class.
```
ossec_syscheck_report_changes_directories_1
ossec_syscheck_max_eps
```

- [ ] The following variables have no effect on manager class.
```
ossec_syscheck_process_priority
ossec_syscheck_synchronization_enabled
ossec_syscheck_synchronization_interval
ossec_syscheck_synchronization_max_eps
ossec_syscheck_synchronization_max_interval
```

- [x] The following `sca_amazon_*` variables don't work on the agent class
```
sca_amazon_enabled
sca_amazon_scan_on_start
sca_amazon_interval
sca_amazon_skip_nfs
sca_amazon_policies
```

- [ ] The following variables have no effect on the agent class.
```
sca_rhel_enabled
sca_rhel_scan_on_start
sca_rhel_interval
sca_rhel_skip_nfs
sca_rhel_policies
```

- [ ] The variable `wazuh_api_cors_allow_headers` produces an error during deployment for the manager.

- [ ] The variable `vulnerability_detector_provider_redhat_os` doesn't work as expected. 

- [ ] The default value of `configure_vulnerability_detector` is `true` instead of `yes`. 

### Other suggestions

- [ ] For all the variables, there is no reference or link about which setting refers to.

- [ ] During our tests, we experienced a consistent issue in which the certificates couldn't be listed in the manager triggering an SSL error. We solved this issue by re-generating the certificates. Maybe we should include a troubleshooting section mentioning that if during the **certificates setup**, the manager returns an error when listing the certificates, they should be regenerated following the next instructions. https://puppet.com/docs/puppet/7/ssl_regenerate_certificates.html#clear_regenerate_certs_on_primary_server

![image](https://user-images.githubusercontent.com/5703274/161086748-70d8587a-5c07-4e50-8ec2-c26501d1d4ce.png)

- [ ] The typo `This files` was found a few times.

- [ ] Would be useful to mention the command `puppet cert sign --all`

**Comment by teddytpc1** [comment]
Regarding `ossec_rootcheck_windows_disabled` variable. The `if`statement should be updated to compare the value against `yes`:
- https://github.com/wazuh/wazuh-puppet/blob/4.3/templates/fragments/_rootcheck.erb#L60-L62

**Comment by teddytpc1** [comment]
Regarding the `ossec_local_files` parameter, I've tested it like this in the agent's manifest:
```
    ossec_local_files => [
            { 'location' => '/var/log2/syslog', 'log_format' => 'syslog' },
            { 'location' => '/var/log2/kern.log', 'log_format' => 'syslog' },
            { 'location' => '/var/log3/auth.log', 'log_format' => 'syslog' },
            { 'location' => '/var/lo4g/dpkg.log', 'log_format' => 'syslog' },
            { 'location' => '/var/ossec/logs/active-responses.log', 'log_format' => 'syslog' },
          ],
```
And it works just fine.
I have also tested with v4.2.6 and v4.3.0 with the default values in `params_manager.pp/params_agent.pp` and it is working for Ubuntu Focal and CentOS 7. Have you checked if the `localfile` configuration is in the CentOS 7 `ossec.conf`? Finally, the `default_local_files` in `params_manager.pp/params_agent.pp` contains a `case` statement in order to have different configurations for each OS family (Debian, RHEL, etc.). If you are going to modify the CentOS `default_local_files` parameter, make sure you are changing the value within the `RedHat` case.

**Comment by pereyra-m** [comment]
Thank you for your comments @teddytpc1 !

I have added some new checks in the description according to the clarifications you provided in https://github.com/wazuh/wazuh-puppet/issues/459.

Regards.

**Comment by teddytpc1** [comment]
Parameter `wazuh_enrollment_enabled` default value is `undef`. If it is not set the complete `enrollment` tag would not be added. So, the enrollment variables will not be present in the `ossec.conf` file if `wazuh_enrollment_enabled` is not set.

**Comment by teddytpc1** [comment]
This should have a boolean `true|false` value instead of `yes|no` in order to the variables to take effect.

**Comment by MiguelazoDS** [comment]
Hi @teddytpc1, 

The same as Matias, I also added some new items in this issue for the comments on these issues. 

- https://github.com/wazuh/wazuh-puppet/issues/464
- https://github.com/wazuh/wazuh-puppet/issues/465
- https://github.com/wazuh/wazuh-puppet/issues/466
- https://github.com/wazuh/wazuh-puppet/issues/467

Thanks.

**Comment by teddytpc1** [comment]
A fix for `sca_amazon_*` variables was added in the PR https://github.com/wazuh/wazuh-puppet/pull/477/files
