### ISSUE TITLE
4.3.0 Getting started enhancement

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4998]
This issue aims to perform a 4.3.0 Getting started enhancement:

# Tasks:

## Stage 1:

- [x] Work on the branch `4.3.0-getting-started-enhancement-v1.0`
- [x] Make the PR #5002 
- [x] Change Use cases structure
    - Erase:
       - security-analytics
       - intrusion-detection
    - Add:
       - rootkits-detection
       - system-inventory
    - Final use cases list:
       - log-analysis
       - file-integrity
       - rootkits-detection
       - incident-response
       - configuration-assessment
       - system-inventory
       - vulnerability-detection
       - cloud-security
       - containers-security
       - regulatory-compliance
- [x] Review grammar
- [x] Review texts from the Gdoc
- [x] Resolve Wazuh components names when needed

## Stage 2:
- [x] Work on the branch `4.3.0-getting-started-enhancement-v2.0`
- [x] Make the PR #5053 
- [x] Add Getting started screenshots.

Regards,
Damian Furfuro
