### ISSUE TITLE
4.3.0 Splunk installation steps doesn't finish with a successfully Splunk-Wazuh environment 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#5024]
[After following the guide ](https://docs.google.com/document/d/15FncJLslUDolQcu_2OHZ0mHtS0dDoBD8orwUIxWbtm4/edit#) we noticed that something is not working on the guide. The following issue comment https://github.com/wazuh/wazuh/issues/12913#issuecomment-1084742999 shows the problems encountered:
- The Splunk indexer installation component should be placed first and then, the Manager and forwarder. 
- Not always is possible to download the Splunk software from the provided link. Maybe this is not our concern, but it happened. 
- Installing and configuring Splunk forwarder finished with a port overlapping with indexer. 
- No alerts were possible to see after the installation.

**Comment by rauldpm** [comment]
### Update report

- Researching the issue and getting familiar with splunk

**Comment by xrisbarney** [comment]
### Update on issue 6. See wazuh alerts:

It looks like splunk is unable to retrieve the alerts when port 9997 is unreachable, occupied or has not been opened. 

I am adding an instruction line to advise users to switch to an alternative port for forwarding.

**Comment by rauldpm** [comment]
### Update report - 8.1.4

- As @xrisbarney mentions, the port 9997 (used by defaults) is not opened (tested two times), had to open a new port and restart the services after adding the new port in Forwarding and receiving
- Still getting  `Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service.`. Testing 8.2.2 to check if is a problem of 8.1.4 version

**Comment by xrisbarney** [comment]
### Docu update

> I have found that the change of the indexer port (troubleshooting) is mandatory in all test i have done. We need to change the default 9997 port since the beginning to avoid this.
I have moved the troubleshooting section to the install and configure splunk indexer instructions as items 4-8. This way, once Splunk is configured before the forwarder is configured with the indexer port we are already using an unused port and there should be no conflicts in outputs.conf.

**Comment by rauldpm** [comment]
### Update report

- Following the new modified guide in single instance, I still get the message:

` ` ` 
Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service
` ` `

- I see that with this guide, the  /opt/splunkforwarder/etc/system/local/outputs.conf is empty when it should contain data
- Adding a new forwarded server, the file is updated with the new server/port indicated without the need to restart the service, this means that the first `add forward-server` command does not work as it should

**Comment by rauldpm** [comment]
### Update report

- After doing research and talking with Christian, we have seen that the guide is designed to build the environment in two nodes (one with splunk enterprise and the other with splunk forwarder), the titles lead to confusion, making us believe that the entire deployment is done on the same node when it is not, it works for deployment on two nodes as Christian has been able to verify
- For the AIO style deployment, some extra steps must be added, I have been doing tests and the basic and minimum configuration to have this type of deployment functional would be following these steps:

<details><summary>AIO deployment for centos (should work using the apt simils)</summary>

```
1. yum install curl -y
2. rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
3. cat > /etc/yum.repos.d/wazuh.repo << EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
EOF
4. yum install -y wazuh-manager
5. systemctl start wazuh-manager
6. yum install splunk-8.2.2.rpm -y
7. curl -so /opt/splunk/etc/system/local/indexes.conf https://raw.githubusercontent.com/wazuh/wazuh-splunk/v4.3.0-8.2.2/setup/indexer/indexes.conf
8. curl -so /opt/splunk/etc/system/local/inputs.conf https://raw.githubusercontent.com/wazuh/wazuh-splunk/v4.3.0-8.2.2/setup/indexer/inputs.conf
9. /opt/splunk/bin/splunk start

(in AIO deplyment its seems mandatory change the default 9997 port)
10. add new port in UI -> eg: 1025

```

![image](https://user-images.githubusercontent.com/14913942/162537527-9bf523e0-560e-4c4d-8e24-fe30ef1f9b72.png)

```

11. /opt/splunk/bin/splunk login
12. /opt/splunk/bin/splunk restart
13. yum install splunkforwarder-8.2.2.rpm -y
14. curl -so /opt/splunkforwarder/etc/system/local/props.conf https://raw.githubusercontent.com/wazuh/wazuh-splunk/v4.3.0-8.2.2/setup/forwarder/props.conf
15. curl -so /opt/splunkforwarder/etc/system/local/inputs.conf https://raw.githubusercontent.com/wazuh/wazuh-splunk/v4.3.0-8.2.2/setup/forwarder/inputs.conf
16. sed -i "s:MANAGER_HOSTNAME:$(hostname):g" /opt/splunkforwarder/etc/system/local/inputs.conf
17. /opt/splunkforwarder/bin/splunk start
18. /opt/splunkforwarder/bin/splunk add forward-server 192.168.57.102:1025
19. /opt/splunkforwarder/bin/splunk restart
20. curl -o SplunkAppForWazuh.tar.gz https://packages-dev.wazuh.com/pre-release/ui/splunk/wazuh_splunk-4.3.0_8.2.2-1.tar.gz
21. /opt/splunk/bin/splunk install app SplunkAppForWazuh.tar.gz
22. /opt/splunk/bin/splunk restart
23. /opt/splunkforwarder/bin/splunk restart

24. Configure API 
(sing in UI)
(Go wazuh plugin) --> username and passwords seems to be already saved with the splunk values (password must be changed to wazuh. Maybe related to splunk login)
(save api configuration)
(access overview -> security events)
(The message Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service will pop up, but we should get events)
```



![f](https://user-images.githubusercontent.com/14913942/162537455-7ad69564-1bb1-454b-b9d3-02884304813f.png)



</details>

- Since the current documentation indicates this type of deployment, we must add the AIO type deployment to the guide with these steps, note that the main difference is the use of splunk login, the initial port change and the multiple necessary restarts
- Generally, from what I have seen, this type of deployment is not recommended in the splunk forums due to performance issues, but for testing they should be useful. Also, although the documentation indicates that this deployment is possible, there are users who indicate that certain commands have problems and step on each other, such as boot start

- https://community.splunk.com/t5/Getting-Data-In/Running-a-Universal-Forwarder-on-the-same-server-as-the/m-p/127676/highlight/true#M26246

![image](https://user-images.githubusercontent.com/14913942/162537136-0fd5fc9d-48b8-492c-bf88-77d3be558f08.png)


- https://community.splunk.com/t5/Getting-Data-In/Install-both-Universal-Forwarder-and-Splunk-Enterprise-on-on/m-p/211042/highlight/true#M41547

![image](https://user-images.githubusercontent.com/14913942/162537256-82ea4e25-5769-4fef-afdc-9208a84d577d.png)

**Comment by rauldpm** [comment]
### TODO

- [ ] Tests versions
  - [x] 8.1.4
  - [x] 8.2.2
  - [ ] 8.2.4 
- [ ] Test API Alias - wazuh-splunk/issues/1145
- [ ] RBAC

**Comment by xrisbarney** [comment]
### Update
- In the single-instance architecture, I have added a prerequisites stating that there should be 2 servers to reinforce that this is a single-instance splunk installation (i.e 1 forwarder, 1 Splunk indexer) but on a multi-tier server (2 servers).

**Comment by xrisbarney** [comment]
### Updated
@rauldpm's Steps worked for the [all-in-one architecture](https://docs.google.com/document/d/1Bf8C90bmcOI_xar5wnDneL2n49kmfNr_3SvREjBIFWc/edit#heading=h.zdm5jf14ajf7).

We now have 3 methods of installing Wazuh with Splunk:
- [All-in-one server architecture](https://docs.google.com/document/d/1Bf8C90bmcOI_xar5wnDneL2n49kmfNr_3SvREjBIFWc/edit#heading=h.zdm5jf14ajf7)
- [Single-instance multi-tier server architecture.](https://docs.google.com/document/d/1Bf8C90bmcOI_xar5wnDneL2n49kmfNr_3SvREjBIFWc/edit#heading=h.k5erd28zskjj) A pre-requisites section was added stating there should be 2 servers.
- [Multi-instance cluster architecture.](https://docs.google.com/document/d/1Bf8C90bmcOI_xar5wnDneL2n49kmfNr_3SvREjBIFWc/edit#heading=h.if01f9fxgbyy)

**Comment by okynos** [comment]
Hello,

Following the documentation guide I have to remark some points that sounds bad for me:
- The `inputs.conf` file provided in the documentation doesn't work for me. I have to modified like this:
```
[splunktcp://9997]
disabled = 0
connection_host = ip
```
- The path described in documentation doesn't let me provide the environment like the path followed in the Indexer/dashboard version (documentation problem).
- Some commands are different from Indexer/dashboard section.
![image](https://user-images.githubusercontent.com/10661307/162730736-24ee9de0-a5db-41e0-8620-d754fe279b1d.png)
![image](https://user-images.githubusercontent.com/10661307/162730766-2901fa7a-5067-4564-854e-cc0f1a891d05.png)
Lacks `curl` to perform the next step.
![image](https://user-images.githubusercontent.com/10661307/162731060-1d295db1-1a0d-45f0-ba5c-71e6c2d8fef2.png)
![image](https://user-images.githubusercontent.com/10661307/162731086-bfc5c748-48d1-4fd7-a847-d8bef5d5b8b5.png)


Considerations:
I have set up two nodes:
1. Splunk indexer
2. Wazuh manager + Splunk forwarder.
The forwarder needs specific configuration.

**Comment by okynos** [comment]
- [x] Test API Alias - WORK AS EXPECTED
![image](https://user-images.githubusercontent.com/10661307/162741026-62d2176c-9572-43fb-a047-cd46a24edff6.png)
- [x] RBAC Test -> https://github.com/wazuh/wazuh-documentation/issues/5057

**Comment by okynos** [comment]
RBAC successfully configured and tested.

**Comment by rauldpm** [comment]
### Update report

- Tested again AIO, some steps can be removed
- In the wazuh cluster desployment, we could add a cluster health check
- I cannot make a single-instance (two nodes - manager+forwarder and enterprise+app) works. API does not show dialogs to connect the api
- We should redefine the deployment methods that we are giving to the user:
  -  AIO
  - minimal splunk distributed architecture (wazuh cluster or single manager?)
  - distributed architecture (wazuh cluster with forwarders, indexer cluster, heads cluster, desployer)
