### ISSUE TITLE
Rework oh the section: `Installation alternatives - Deployment on Docker`

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5088]
This issue aims to rework the section: `Installation alternatives - Deployment on Docker`.

## Tasks:

- [ ] Work on the branch 
- [ ] Make the PR #
- [ ] Copy the new content from the Google doc to this section of the documentation.
