### ISSUE TITLE
Rework the Getting started section

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5122]
This issue aims to rework the `Getting started` section.

## Tasks:
- [x] Work on the branch `4.3.0-getting-started-rework.`
- [x] Work on the PR #5124
- [x] Create new content and copy it from the Google doc to the documentation.
- [x] Ask the content team to review it.
