### ISSUE TITLE
Documentation SemRush issues 2022

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5267]
This issue aims to list and correct the Wazuh documentation SemRush issues for 2022:

# May 2022

## Task 1
- [x] Pages don´t have meta descriptions
    - [x] Work on the branch `4.3-add-meta-descriptions`
    - [x] Work on the PR #5279
    - [x] Add meta descriptions to the pages that don´t have and the other pages on each sections
    - [x] Review and make all the meta descriptions consistent
    - [x] Ask the content team for a review

## Task 2
- [x] Improve anchor texts where resources are formatted as the page link in 4.3
    - [x] Work on the branch `4.3-improve-anchor-texts`
    - [x] Work on the PR #5303
    - [x] Improve anchor texts 
    - [x] Review and make all the anchor texts consistent
    - [x] Ask the content team for a review

## Task 3
- [x] Improve anchor texts where resources are formatted as the page link in 4.4
    - [x] Work on the branch `4.4-improve-anchor-texts`
    - [x] Work on the PR #5356
    - [x] Improve anchor texts 
    - [x] Review and make all the anchor texts consistent
    - [x] Ask the content team for a review
