### ISSUE TITLE
Edit content about the dashboard tab of the vulnerabilities module

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5274]
This issue aims to edit content about the dashboard tab of the vulnerabilities module in the Wazuh dashboard because this tab was removed.

## Introduction
- The dashboard tab of the vulnerabilities module was removed:
![image (3)](https://user-images.githubusercontent.com/85168963/170536907-6ce797fe-1fbf-4087-83de-ed7afee881b6.png)

- So now users need to select an agent in the inventory tab to access information about the vulnerabilities inventory:
![image (2)](https://user-images.githubusercontent.com/85168963/170536979-f25eff1c-58a2-46ab-9344-a2d5a580c578.png)

-As there is content about this capability in the documentation, we need to adjust it to fit the current state of the Wazuh dashboard:
![image (4)](https://user-images.githubusercontent.com/85168963/170537844-87de795c-194d-4335-9f42-8fae2e347714.png)

## Tasks
- [x] Create the branch `4.3-dashboard-tab-vulnerabilities-module`
- [x] Create the PR #5275
- [x] Search content about the dashboard tab of the vulnerabilities module in the Wazuh documentation
- [x] Edit each content and update it
- [ ] Check that edited content with the documentation team.
