### ISSUE TITLE
Wazuh 4.3.2 - 4.2.7 - 3.13.4 release notes and version update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5283]
This issue aims to create the Wazuh 4.3.2 - 4.2.7 - 3.13.4 release notes and version update:

# Tasks

## 4.2.7 Release notes
- [x] Work on the branch `4.2.7-release-notes`
- [x] Work on the PR #5284 
- [x]  Create the 4.2.7 Release notes
- [x] Share with content team.

## 4.3.2 Release notes
- [x] Work on the branch `4.3.2-release-notes`
- [x] Work on the PR #5285
- [x]  Create the 4.3.2 Release notes
- [x] Share with content team.

## 3.13.4 Release notes
- [x] Work on the branch `3.13.4-release-notes`
- [x] Work on the PR #5286
- [x]  Create the 3.13.4 Release notes
- [x] Share with content team.

## Add Release note 3.13.4 to 4.1
- [x] Work on the branch `Add-release-note-3.13.4-to-4.1`
- [x] Work on the PR #5287
- [x] Add Release note 3.13.4 to 4.1
- [x] Share with content team.

## Add Release note 3.13.4 to 4.0
- [x] Work on the branch `add-release-note-3.13.4-to-4.0`
- [x] Work on the PR #5292
- [x] Add Release note 3.13.4 to 4.0
- [x] Share with content team.

## Add Release note 3.13.4 to 4.2
- [x] Work on the branch `add-release-note-3.13.4-to-4.2`
- [x] Work on the PR #5293
- [x] Add Release note 3.13.4 to 4.2
- [x] Share with content team.

## Add Release note 3.13.4 to 4.3
- [x] Work on the branch `add-release-note-3.13.4-to-4.3`
- [x] Work on the PR #5294
- [x] Add Release note 3.13.4 to 4.3
- [x] Share with content team.
