### ISSUE TITLE
Improve the links and index pages of some sections

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5313]
## Description

We can find some titles than don't have links in the index of the documentation, such as the `User Manual` or `Cloud security`. Besides, some of these sections don't have proper intro text on their index pages. So this issue aims to improve the links and index pages of some sections of the documentation.

This issue aims to  Improve the index pages and display the links of several sections in the index of the documentation.

## Task
- [x] Display link of the following sections in the index of the documentation:
     - [x] Migration guide
     - [x] User manual
     - [x] Cloud security
     - [x] Development
     - [x] Compliance
- [x] Improve the index page of the following sections:
     - [x] Migration guide
     - [x] User manual
     - [x] Cloud security
     - [x] Development
     - [x] Compliance
- [x] Work on the branch `4.3-improve-user-manual-index`
- [x] Work on the PR #5425
- [x] Ask for review.
