### ISSUE TITLE
Change command in the macOS agent installation from sources

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5332]
## Description

This issue aims to change a wrong command in the macOS agent installation from sources:
![image](https://user-images.githubusercontent.com/85168963/172613721-37f505e4-81b1-41fc-a046-27517eb0ed6d.png)

## Tasks:
- [x] Work on the branch `macos-agent-installation`
- [x] Work on the PR #5333
- [x] Review the changes
- [x] Share with the content team.
