### ISSUE TITLE
Add wazuh/wazuh-packages issues to Wazuh v4.3.4 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5339]
## Description:

This issue aims to add wazuh/wazuh-packages issues to Wazuh v4.3.4 release notes.

## Tasks:
- [x] Work on the branch `add-packages-issues-to-4.3.4-release-notes`
- [x] Work on the PR #5340
- [x] Add wazuh/wazuh-packages issues to Wazuh v4.3.4 release notes
- [x] Share with content team.
