### ISSUE TITLE
Review the `Installation guide` Google doc

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5350]
## Description

This issue aims to review the `Installation guide`  Google doc to maintain it up to date with the documentation:

##Tasks
- [x] Review each page of this section with the Github Blame tool to find changes in the last weeks   
- [x] Compare with the `Installation guide`  Google doc
- [x] Leave comments in the doc
- [x] Ask the content team to edit the doc.
