### ISSUE TITLE
Improve the text structure of the section: Running a vulnerability scan

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5367]
## Description
This issue aims to improve the text structure of the section: User manual / Capabilities / Vulnerability detection / Running a vulnerability scan.

## Tasks
- [x] Work on the branch `running-vulnerability-scan-structure-improve`
- [x] Work on the PR #5395
- [x] Improve the text structure of the section: Running a vulnerability scan
- [x] Ask the documentation team to review it.
