### ISSUE TITLE
Wazuh 4.3.5 release notes and version update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5370]
## Description

This issue aims to create the Wazuh v4.3.5 release notes and version updates throughout the documentation.

## Stage 1
- [x] Work on the branch `4.3.5-release-notes-and-version-update`
- [x] Work on the PR #5371
- [x] Create the 4.3.5 Release notes
- [x] Add issues from wazuh/wazuh
- [x] Add issues from wazuh/wazuh-dashboard
- [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
- [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
- [x] Add issues from wazuh/wazuh-splunk
- [x] Add issues from wazuh/wazuh-packages
- [x] Make a versions update
- [x] Share with the content team

## Stage 2
- [x] Work on the branch `4.3.5-release-notes-revision`
- [x] Work on the PR #5394
- [x] Make a release notes revision.
- [x] Share with the content team
