### ISSUE TITLE
EPIC: Documentation editorial and grammar review

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5396]
This epic issue aims to perform an editorial and grammar review of the documentation:

## Tasks
- Perform the following tasks:
    - Review the grammar
    - Review the text structure: 
       - Text-formatting 
       - Numbered lists/steps
       - buttons and icons
    - Improve the link structure from `:ref:` to `:doc:` when needed
    - Resolve Wazuh components names when needed
    - Review unnecessary apostrophes in our documentation. When two nouns are together, and the first noun works as an adjective, no apostrophe is needed. See more information [here](https://theeditorsblog.net/2018/02/10/am-i-possessive/)
    - Review the text style according to the **Wazuh Style Guide for Technical Writing**
    - Use of Commonly used contractions such as isn’t, aren’t, can’t, doesn’t, don’t, haven’t, wasn’t, weren’t, etc. 
    - Remove historical references that are not necessary.

## Editorial review
- Review the following sections of the documentation:
- [x] Getting started with Wazuh
- [x] Quickstart
- [x] Installation guide
- [x] Installation alternatives
- [x] Upgrade guide
- [x] Cloud service
- [x] User manual (agent-enrollment to ruleset) 
- [x] User manual (securing-wazuh to wazuh-dashboard) 
- [x] Cloud security
   - [x] Using Wazuh to monitor AWS
   - [x] Using Wazuh to monitor Microsoft Azure
   - [x] Using Wazuh to monitor GitHub
   - [x] Using Wazuh to monitor GCP services
   - [x] Using Wazuh to monitor Office 365
- [ ] Container security 
- [ ] Development
- [ ] Compliance (wait the new version) 
- [ ] Learning Wazuh (wait the new version)
- [ ] Proof of Concept guide (wait the new version) 
- [ ] Release notes.

## Link structure
- Review the following sections of the documentation:
- [x] Getting started with Wazuh
- [x] Quickstart
- [x] Installation guide
- [x] Installation alternatives
- [ ] Upgrade guide
- [ ] Cloud service
- [ ] User manual (wait the new version) 
- [ ] Cloud security
   - [ ] Using Wazuh to monitor AWS
   - [ ] Using Wazuh to monitor Microsoft Azure
   - [ ] Using Wazuh to monitor GitHub
   - [ ] Using Wazuh to monitor GCP services
   - [ ] Using Wazuh to monitor Office 365
- [ ] Container security 
- [ ] Development
- [ ] Compliance (wait the new version) 
- [ ] Learning Wazuh (wait the new version)
- [ ] Proof of Concept guide (wait the new version) 
- [ ] Release notes.

**Comment by Arcapas** [comment]
This issue is now closed since we have released multiple new sections that have undergone editorial and grammar reviews.
