### ISSUE TITLE
Change the Wazuh dashboard release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5402]
## Description

This issue includes a change in the Wazuh dashboard release notes.

## Tasks
- [x] Work on the branch `dashboards-release-notes-revision`
- [x] Work on the PR #5401
- [x] Make a change in the Wazuh dashboard release notes
- [ ] Share with the documentation-team.

**Comment by Arcapas** [comment]
We decided to use the existing option.
