### ISSUE TITLE
Editorial and grammar review: Using Wazuh to monitor AWS

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5406]
This issue aims to perform an editorial and grammar review of Using Wazuh to monitor AWS:

# Tasks:
- [x] Work on the branch: `4.3.0-grammar-review-5`
- [x] Work on PR #5398
- [x] Ask the content team for a review.
