### ISSUE TITLE
Editorial and grammar review: `Using Wazuh to monitor Microsoft Azure`

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5413]
## Description
This issue aims to perform an editorial and grammar review of `Using Wazuh to monitor Microsoft Azure`.

# Tasks:
- [x] Work on branch `4.3-azure-grammar-review`
- [x] Work on PR #5465
- [x] Ask for review.
