### ISSUE TITLE
Improve pages links: `Installation alternatives` 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5418]
## Description
This issue aims to improve the links in the `Installation alternatives` section.

## Task
- [x] Improve pages links on  `Installation alternatives` section:
    - [x] amazon-machine-images
    - [x] deploying-with-ansible
    - [x] deploying-with-kubernetes
    - [x] deploying-with-puppet
    - [x] docker
    - [x] elastic-stack
    - [x] splunk
    - [x] virtual-machine
    - [x] wazuh-from-sources
- [x] Work on the branch `4.3-improve-links-installation-alternatives`
- [x] Work on the PR #5460
- [x] Review the changes
- [x] Ask review.
