### ISSUE TITLE
Wazuh 4.3.6 release notes and versions update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5420]
## Description

This issue aims to create the Wazuh v4.3.6 release notes and versions update throughout the documentation.

## Tasks
- [x] Branch `4.3.6-release-notes-and-version-updates-v2`
- [x] PR #5462
- [x] Create the 4.3.6 Release notes
- [x] Add issues:
    - [x] Add issues from wazuh/wazuh
    - [x] Add issues from wazuh/wazuh-dashboard
    - [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [x] Add issues from wazuh/wazuh-splunk
    - [x] Add issues from wazuh/wazuh-packages
- [x] Make a versions update
- [x] Ask review.
