### ISSUE TITLE
Change command `apt` with `apt-get`

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5454]
## Description
This issue aims to change command `apt` with `apt-get` to support older systems. 
This issue is referenced and closes the issue https://github.com/wazuh/wazuh-documentation/issues/5381

## Tasks
- [x] Make a review of the documentation and change command `apt` with `apt-get` 
- [x] Work on the branch `4.3-change-apt-to-apt-get`
- [x] Work on the PR #5455
- [x] Ask review.
