### ISSUE TITLE
Update a query in the Indices configuration for Elasticsearch

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5485]
## Description

This issue aims to update a query in the Indices configuration for Elasticsearch.

## Tasks
- [x] Branch `4.3-update-query-indices-configuration`
- [x] PR #5486
- [x] Update a query in the Indices configuration for Elasticsearch
- [x] Ask for review.
