### ISSUE TITLE
Rework of the Regulatory compliance section

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5491]
## Description
This issue aims to make a rework of the `Regulatory compliance` section.

## Tasks
- [x] Branch: `4.3-regulatory-compliance-rework`
- [x] PR: #5492
- [x] make a rework of the `Regulatory compliance` section
- [x] Move the content from the doc to the documentation
- [x] Review the new content
- [x] Ask for a review from the documentation team
- [x] Receive a new version of the doc with changes
- [x] Move the new content from the doc to the documentation
- [x] Review the new content
- [x] Ask for a review from the documentation team
