### ISSUE TITLE
Documentation meta-descriptions review N° 2

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5498]
## Description
This issue aims to perform a meta-descriptions review of the documentation.

## Tasks
- [x] Branch `4.3-add-meta-descriptions-v4`
- [x] PR #5518
- [x] Review the following sections of the documentation searching for missing meta-descriptions:
    - [x] Upgrade guide
    - [x] Cloud service
    - [x] Cloud security
        - [x] amazon
        - [x] azure
        - [x] github
        - [x] gcp
        - [x] office365
- [x] Review and make all the meta-descriptions consistent
- [x] Ask the content team to review it
- [x] Make a 2nd review to make all the meta-descriptions consistent
- [x] Improve AWS based services meta-descriptions
- [x] Ask the content team to review it.
