### ISSUE TITLE
Editorial and grammar review: Cloud security

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5534]
## Description
This issue aims to perform an editorial and grammar review of the following sections of `Cloud security`:
- Using Wazuh to monitor GitHub
- Using Wazuh to monitor GCP services
- Using Wazuh to monitor Office 365

## Tasks:
- [x] Branch `5534-cloud-security-grammar-review`
- [x] PR #5703
- [x] perform an editorial and grammar review of:
   - [x] Using Wazuh to monitor GitHub
   - [x] Using Wazuh to monitor GCP services
   - [x] Using Wazuh to monitor Office 365
- [x] Ask for a review.
