### ISSUE TITLE
Add breaking changes section in the release notes of Wazuh 4.3.0

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5538]
## Description
This Issue refers to issue #5532 and aims to research and add a breaking changes section in the release notes of Wazuh 4.3.0.

## Tasks
- [x] Make some research
- [ ] Add a breaking changes section
- [ ] Branch:
- [ ] PR:
- [ ] Ask for a review.
