### ISSUE TITLE
Add documentation to install on Alpine Linux from sources

### ISSUE THREAD

**Issue by FrancoRivero** [wazuh/wazuh-documentation#5539]
## Description
This issue aims to perform an editorial and grammar review of the following sections of `Installing the Wazuh agent from sources`:
- Install Wazuh on Alpine Linux from sources

## Tasks:
- [x] Work on branch `5539-agent-build-alpine-linux`
- [x] perform an editorial and grammar review of:
   - [x] Install Wazuh on Alpine Linux from sources
- [x] Work on PR
- [x] Ask for a review.
