### ISSUE TITLE
Documentation meta-descriptions review N° 3

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5546]
## Description
This issue aims to perform a meta-descriptions review of the documentation.

## Tasks
- [x] Branch `4.3-add-meta-descriptions-v5`
- [x] PR #5547
- [x] Review meta-descriptions from the PR #4566
- [x] Review the following sections of the documentation searching for missing meta-descriptions:
    - [x] Container security
    - [x] Development
    - [x] Release notes
    - [x] `pci-dss` from the PR #5492 
- [x] Review and make all the meta-descriptions consistent
- [x] Ask the content team to review it.
