### ISSUE TITLE
Documentation meta-descriptions review N° 4

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5550]
## Description
This issue aims to perform a meta-descriptions review of the documentation.

## Tasks
- [x] Branch `4.3-add-meta-descriptions-v6`
- [x] PR #5558
- [x] review the SemRush issues for September 2022
- [x] Review the following sections of the documentation searching for missing meta-descriptions:
    - [x] User manual
         - [x] `user-manual/agent-enrollment` to `user-manual/registering` 
- [x] Review and make all the meta-descriptions consistent
- [x] Ask the documentation team to review it.
