### ISSUE TITLE
Update of Wazuh 4.3.7 release notes 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5554]
## Description
This issue aims to make an update of Wazuh 4.3.7 release notes.

## Tasks
- [x] Branch: `4.3.7-release-notes-update-v1`
- [x] PR: #5555
- [x] Make an update to the Wazuh v4.3.7 release notes
- [ ] Ask for a review.
