### ISSUE TITLE
Update the section: Regulatory compliance 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5556]
## Description
This issue aims to update the `Regulatory compliance` section.

## Tasks
- [x] Branch: `4.3-regulatory-compliance-update-v1`
- [x] PR: #5557
- [x] Update the `Regulatory compliance` section
- [x] Ask for a review.

**Comment by Arcapas** [comment]
We are putting this issue on hold until further notice.
