### ISSUE TITLE
EPIC: Documentation meta-descriptions

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5564]
A [meta description](https://www.semrush.com/blog/what-not-to-do-when-writing-a-meta-description/) is an HTML tag used to describe the content of a web page. This description will show up below the title and URL of your page as it appears in the search engine results. In order to remain visible within Google, your meta description should be kept somewhere between 140-160 characters.

This epic issue aims to perform a meta-descriptions review of the documentation and keep track of all of them according to the following tasks:

## Tasks
Review the following sections of the documentation searching for missing meta-descriptions:
- #5424
- [x] Getting started with Wazuh
- [x] Quickstart
- [x] Installation guide
- [x] Installation alternatives 
-  #5498
- [x] Upgrade guide 
- [x] Cloud service
- [x] Cloud security
- #5546
- [x] Container security
- [x] Development
- [x] Release notes
- #5550
- [x] User manual
    - [x] user-manual/agent-enrollment to user-manual/registering
- #5598
- [x] User manual
    - [x] user-manual/ruleset to user-manual/wazuh-dashboard
- [x] Compliance
- [x] Learning Wazuh
- [x] Proof of Concept guide.
