### ISSUE TITLE
Rewording and change wrong image in the `Cloud security` section from 4.0 to 4.3

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5565]
## Description
This issue aims to make a rewording and change the wrong image in the `Create a subscription` field of the `Cloud security` section in versions 4.0, 4.1, 4.2, and 4.3.

##  Tasks
**Branch 4.2**
- [x] Make a rewording and change the wrong in branch 4.2
- [x] Change images with new ones with blurred info
- [x] Branch `5565-change-image`
- [x] PR #5567
- [x] PR #5633

**Branch 4.1**
- [x] Make a rewording and change the wrong in branch 4.1
- [x] Branch `5565-change-image-4.1`
- [x] PR #5607

**Branch 4.0**
- [x] Make a rewording and change the wrong in branch 4.0
- [x] Branch `5565-change-image-4.0`
- [x] PR #5609

**Branch 4.3**
- [x] Make a rewording in branch 4.3
- [x] Branch `5565-change-image-4.3`
- [x] PR #5612
- [x] Ask for a review
