### ISSUE TITLE
Update AWS error codes reference

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh-documentation#5570]
## Description

This issue is intended to make a review of the error codes present in [source/amazon/services/troubleshooting.rst](https://github.com/wazuh/wazuh-documentation/blob/4ebe8fea75792db0f7f9880e6d63065286f2b964/source/amazon/services/troubleshooting.rst), replacing existing information or adding new information if necessary, as well as adding any missing error codes to the table.

In particular, we are aware that we are currently missing error codes `18` and `19`.

The full error code list can be found in [wazuh/wodles/aws/aws_s3.py](https://github.com/wazuh/wazuh/blob/8b4624107d36970222425dfa8336a487eee4b963/wodles/aws/aws_s3.py).

## Tasks
- [x] Add error codes `18` and `19` to the troubleshooting documentation.
- [x] Review every existing error code in the troubleshooting documentation and improve their description if required.
- [x] Remove any unused error code, if present.
