### ISSUE TITLE
Include a documentation page to explain a single node addition 

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#5579]
Hello all,

## Description

We need to include into our documentation pages a way to manage nodes addition to a pre-existing Wazuh indexer cluster.
Currently, the way to add a node is described here https://github.com/wazuh/wazuh-packages/issues/1530#issuecomment-1241743340
When the mentioned issue is completed we will need to modify such documentation to adapt the new model.

## Tasks
- [ ] Include `Add Wazuh indexer node` documentation page
  - [ ] Include the steps referred by the issue
- [ ] When the issue is completed update the mentioned documentation

## Validators
- [ ] @alberpilot 
- [ ] @DFolchA 
- [ ] @okynos 
- [ ] @s-ocando 
- [ ] @javimed

**Comment by AlexRuiz7** [comment]
https://documentation.wazuh.com/current/user-manual/wazuh-indexer-cluster/add-wazuh-indexer-nodes.html
