### ISSUE TITLE
Review and improve the content of the CPE Helper documentation

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-documentation#5581]
## Description

We should review the [CPE Helper documentation](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html#products-whose-version-does-not-change-between-updates) and improve it to make it more user-friendly. To do this, it is necessary to unify the use of some words, restructure the document to try to repeat as little as possible and reorder some tables, among other things.

To this end, I propose below a list of tasks based on a previous review:

### Tasks
- [ ] Perform another review of the [CPE Helper](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html#products-whose-version-does-not-change-between-updates) to restructure it in the best possible way and add more tasks if needed.
- [ ] In the `Dictionary Schema`, review and modify what we call `section` and `field`, to keep it simple. 
  > Ex: section should not be used for a field in a JSON.
- [ ] Reorder the Translation types table by field groupings, instead of action type. I.e.:
  ```
  ...version_if...
  ...version_only_if...
  ...update_if...
  ...update_only_if...
  ```
- [ ] Restructure the `use cases` to try not to repeat steps and make it useful for the user.
