### ISSUE TITLE
Documentation meta-descriptions review N° 5

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5598]
## Description
This issue aims to perform a meta-descriptions review of the documentation.

## Tasks
- [x] Branch `5564-add-meta-descriptions-n5`
- [x] PR #5605
- [x] Review the following sections of the documentation searching for missing meta-descriptions:
    - [x] User manual: From `user-manual/ruleset` to `user-manual/wazuh-dashboard`   
    - [x] Compliance
        - [x] pci-dss
        - [x] gdpr 
    - [x] Learning Wazuh
    - [x] Proof of Concept guide.
- [x] Review and make all the meta-descriptions consistent
- [x] Ask the content team to review it.
