### ISSUE TITLE
Correction in the section: Detecting an SQL Injection attack

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5606]
## Description
This issue aims to make a correction in the section: [Detecting an SQL Injection attack](https://documentation.wazuh.com/current/proof-of-concept-guide/detect-web-attack-sql-injection.html):

- A community user reported documentation on this [page](https://documentation.wazuh.com/current/proof-of-concept-guide/detect-web-attack-sql-injection.html) about `detecting SQL injection attack` is not accurate. 
- A Frontend team member performed the steps with a fresh install of the apache2 server, and the rule triggered is the number 31106 (child of 31103, when HTTP response code is 200). 
- We will update the page to explain better that children's rules of 31103 would match instead, depending on the apache server setup.

##  Tasks
- [x] Update the section [Detecting an SQL Injection attack](https://documentation.wazuh.com/current/proof-of-concept-guide/detect-web-attack-sql-injection.html) 
- [x] Work on branch: `5606-detecting-SQL-Injection-attack`
- [x] Work on PR: #5702
- [x] Review and make the text consistent
- [x] Ask the team to review it.
