### ISSUE TITLE
Update the section: Installation guide

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5631]
## Description
This issue aims to update the `Installation guide` section according to the new doc about this unit.

## Tasks
- [x] Review the new Google doc about this section and make suggestions to the authors
- [x] Branch: `5631-installation-guide-update`
- [x] PR: #5756
- [x] Update the `Regulatory compliance` section
- [x] Review all the changes
- [x] Ask for a review.
