### ISSUE TITLE
Update the section: User manual / Single sign on 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5641]
## Description
This issue aims to update the `User manual` section according to the new doc about this unit.

## Tasks: Add the `Single sign on` new section
- [x] Review the new Google doc about this section and make suggestions to the authors
- [x] Add the `Single sing on` section
- [x] Branch: `5641-add-single-sign-on`
- [x] PR: #5650
- [x] Make a complete review
- [x] Ask for a review.
