### ISSUE TITLE
Review the section: Deployment on Docker

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5648]
## Description
This issue aims to review the update of the `Deployment on Docker` section according to the new doc.

## Tasks
- [x] Review the PR #5759
- [x] Make the needed suggestions
- [x] Notify the team that the review is ready
