### ISSUE TITLE
Add changes to SCA documentation to add new regex implementation

### ISSUE THREAD

**Issue by FrancoRivero** [wazuh/wazuh-documentation#5652]
## Description
This issue aims to perform an editorial and grammar review of the following sections of `Security Configuration Assessment`:
- Modify the documentation to accommodate the new regex engine information.

## Tasks:
- [x] Work on branch `5652-add-changes-to-SCA-documentation`
- [x] perform an editorial and grammar review of:
   - [x] Changes on Security Configuration Assessment 
- [x] Work on PR
- [x] Ask for a review.
