### ISSUE TITLE
Update gcp-bucket and gcp-pubsub references

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-documentation#5699]
During the manual testing it has been detected that there are several fixed to be applied in the reference page for both `gcp-bucket` and `gcp-pubsub` integrations. Specifically, the problems to review are the following:

### Invalid configuration example for gcp-bucket

The following configuration example appears at the end of the documentation:
```
<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1m</interval>
    <project_id>wazuh-dev</project_id>
    <subscription_name>wazuhdns</subscription_name>
    <credentials_file>wodles/gcp-bucket/credentials.json</credentials_file>
</gcp-bucket>
```

This configuration is invalid as it includes multiple parameters that are unique to `pubsub`, such as `project_id` or `subscription_name`. We need to replace this configuration with a valid one and check the rest of the documentation to make sure this error is not repeated on other pages.

### Invalid descriptions for gcp-pubsub options

Some option descriptions are too ambiguous while others are just plain wrong. An example would be the credentials parameter, which states that `it allows both relative (to $HOME_INSTALLATION) and absolute paths`. This is not true. This particular option only accepts absolute paths.

We need to check the rest of the parameters to make sure there are no similar errors.

### Missing valid examples for the gcp-pubsub and gcp-bucket options

Some option such as `only_logs_after` are missing valid examples to show the user how to use them.

## Tasks

- [ ] Review and update every gcp-bucket configuration example
- [ ] Review and update the different parameters for gcp-bucket
- [ ] Review and update the different parameters for gcp-pubsub

**Comment by GGP1** [comment]
## Update

### Invalid configuration example for gcp-bucket

This issue was fixed in https://github.com/wazuh/wazuh-documentation/pull/6509

### Invalid descriptions for gcp-pubsub options

Relative paths are supported but they must be relative to `$HOME_INSTALLATION`, changed the phrasing to make it more clear.

### Missing valid examples for the gcp-pubsub and gcp-bucket options

I think the options' descriptions should be explained in detail rather than including configuration examples for each one of them. I reviewed the existing descriptions and applied improvements where I considered appropriate.

**Comment by GGP1** [comment]
## Update

Created a table for the bucket options and modified the order of the parameters to make them easier to read.

**Comment by GGP1** [comment]
## Update

Applied code review suggestions.
