### ISSUE TITLE
Unify instructions for restarting services 

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#5705]
## Description
In many sections, we still find old instructions for restarting the Wazuh manager that does not include the tabs for _Systemd_ and _SysV Init_. 

For example, [VirusTotal integration > Using FIM to monitor a directory](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/integration.html#using-fim-to-monitor-a-directory): 

![image](https://user-images.githubusercontent.com/61882981/197820043-0617da6c-34b9-4111-a818-eebfec996d6c.png)

We should replace them with the new templates, to gain uniformity throughout the documentation and make them easier to maintain. We should also update the instructions to restart the Wazuh agents, and Filebeat, among others.

![image](https://user-images.githubusercontent.com/61882981/197821146-0648423a-da97-4738-b3a1-1fa89775d679.png)

## Tasks:
- [x] Branch: `5705-unify-instructions-for-restarting-services`
- [x] PR: #5706
- [x] Replace old instructions for restarting services with new templates
- [x] Make a complete review of all the changes
- [x] Ask for a review.
