### ISSUE TITLE
Update the section: Using Wazuh for PCI DSS compliance

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5713]
## Description
This issue aims to update the section `Using Wazuh for PCI DSS compliance`.

## Tasks
- [x] Branch: `5713-pci-dss-compliance-update`
- [x] PR: #5715
- [x] Update the `Using Wazuh for PCI DSS compliance` section
- [x] Ask the web team to upload an attached file
- [x] Ask for a review of the team.
