### ISSUE TITLE
Change the links on the section: Restore the Wazuh alerts from Wazuh 2.x

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5717]
## Description
This issue aims to Change the links in the section: `Restore the Wazuh alerts from Wazuh 2.x`:
 
- The links to the files mentioned in this section are not working: [Restore the Wazuh alerts from Wazuh 2.x](https://documentation.wazuh.com/current/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.html#restore-the-wazuh-alerts-from-wazuh-2-x):
   - [restore_alerts.sh](https://github.com/wazuh/wazuh/tree/master/extensions/elasticsearch/restore_alerts/restore_alerts.sh)
   - [restore_alerts.conf](https://github.com/wazuh/wazuh/tree/master/extensions/elasticsearch/restore_alerts/restore_alerts.conf)
- The master branch no longer contains such files. Instead, we need to change the links and use the ones on this [path](https://github.com/wazuh/wazuh/tree/v3.13.6/extensions/elasticsearch/restore_alerts):
   - [restore_alerts.sh](https://github.com/wazuh/wazuh/blob/v3.13.6/extensions/elasticsearch/restore_alerts/restore_alerts.sh)
   - [restore_alerts.conf](https://github.com/wazuh/wazuh/blob/v3.13.6/extensions/elasticsearch/restore_alerts/restore_alerts.conf)

## Tasks: 
- [x] Change the links in the section: `Restore the Wazuh alerts from Wazuh 2.x`
- [x] Branch: `5717-fix-broken-links`
- [x] PR: #5721
- [x] Make a complete review
- [x] Ask for a review.

**Comment by Arcapas** [comment]
Change link:
https://github.com/wazuh/wazuh/tree/v3.13.6/extensions/elasticsearch/restore_alerts

By:
https://github.com/wazuh/wazuh/tree/3.13/extensions/elasticsearch/restore_alerts
