### ISSUE TITLE
Review the section: User manual / Single sign-on

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5718]
## Description
This issue aims to review the section `User manual / Single sign-on`.

## Tasks: 
- [x] Review the section `User manual / Single sign-on`
- [x] PR: #5719
- [x] PR: #5720
- [x] Make a complete review
- [x] Ask for a review.
