### ISSUE TITLE
Editorial and grammar review: User manual

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5722]
## Description
This issue aims to perform an editorial and grammar review of the sections `User manual`. From `Securing Wazuh` to `Uninstalling the Wazuh components`.

## Tasks:
- [x] Branch: `5722-user-manual-grammar-review`
- [x] PR: #5723
- [x] Perform an editorial and grammar review  of the following sections:
   - [x] User manual / Securing Wazuh
   - [x] User manual / Reference
   - [x] User manual / Elasticsearch
   - [x] User manual / Wazuh dashboard
   - [x] User manual / Uninstalling the Wazuh components
- [x] Merge remote-tracking branch `origin/4.3`
- [x] Make a complete review of all the corrections
- [x] Ask for a review.

**Comment by Arcapas** [comment]
I'm working on the path: [User manual](https://github.com/wazuh/index.html)[Reference](https://github.com/wazuh/wazuh-documentation/index.html)[Local configuration (ossec.conf)](https://github.com/wazuh/wazuh-documentation/issues/index.html)fluent-forward
