### ISSUE TITLE
Adjust `SysV init` instructions

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5729]
## Description
This issue aims to adjust `SysV init` instructions throughout the documentation.

## Tasks: 
- [ ] Adjust `SysV Init` instructions throughout the documentation
- [ ] Branch: 
- [ ] PR: 
- [ ] Make a complete review
- [ ] Ask for a review.
