### ISSUE TITLE
Fix EICAR URL

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5735]
## Description
This issue aims to fix the broken EICAR download link in the documentation.
based on PR [#5499](https://github.com/wazuh/wazuh-documentation/pull/5499).

## Tasks
- [x] Fix the broken EICAR download link in the documentation 
- [x] Branch: `5735-fix-eicar-url`
- [x] PR: #5754
- [x] Make a complete review
- [x] Ask for a review.
