### ISSUE TITLE
Vulnerability detector guide update

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-documentation#5762]
## Description

The new Vulnerability Detector guide was published recently ([Vulnerability detection](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html)) but there are some details in the first section that are too technical and/or advanced and might be better to move/adapt them.

It happens that the internal DB `/var/ossec/queue/vulnerabilities/cve.db` should be mentioned after the general behavior of the scanner is detailed and not at the beginning. Consider that accessing this database isn't required in any normal use case of Vulnerability Detector and that its schema isn't detailed in the documentation. The user needs some guidance before getting something useful from it.

## Tasks

It is proposed to create a new section with these advanced details, and some common questions about the module.
But this is only a suggestion.

- [ ] Move the reference to the internal DB to another section that isn't the beginning 
- [ ] List what are the tables that have information about the CVEs and what are the tables used internally during the scan and shouldn't be touched
- [ ] Provide a simple example of a query because the schema of the database isn't described in the docs
