### ISSUE TITLE
Update the Packages list tables location

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5796]
## Description
This issue aims to update the Packages list tables location.

## Tasks
- [x] Branch: `5796-update-packages-list-tables-location`
- [x] PR: #5797
- [x] Update the Packages list tables location of the following sections:
    - [x] Installing Wazuh with Splunk
    - [x] Installing Wazuh with Elastic Stack
    - [x] Amazon Machine Images
    - [x] Virtual Machine (OVA)
- [x] Make a complete review
- [x] Ask for a review.
