### ISSUE TITLE
Update Single sign-on on V4.4

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5807]
## Description
This issue aims to update the `Single sign-on` section on V4.4 according to the new Google doc.

## Tasks
- [ ] Work with the new Google doc: Single Sign On v4.4
- [ ] Update the `Single sign-on` section
- [ ] Branch: 
- [ ] PR: 
- [ ] Make a complete review
- [ ] Ask for a review.
