### ISSUE TITLE
Update the section: Listing agents using the Wazuh app

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5809]
## Description
This issue aims to update the `Listing agents using the Wazuh app` section.

## Tasks
- [x] Update the `Listing agents using the Wazuh app` section
- [x] Branch: `5809-update-listing-agents-using-the-wazuh-app`
- [x] PR: #5810
- [x] Make a complete review
- [x] Ask for a review.
