### ISSUE TITLE
 Add the new section Keycloak in SSO 4.4

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5814]
## Description
This issue aims to add the new section `Keycloak` in SSO 4.4 according to the new Google doc.

## Tasks
- [x] Work with the new Google doc: Single Sign On v4.4
- [x] Branch: `5814-add-keycloak-to-sso-4.4`
- [x] PR: #5815
- [x] Add the new section Keycloak in SSO 4.4
- [x] Make a complete review
- [ ] Ask for a review.
