### ISSUE TITLE
Update section Single sign-on for 4.3

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5830]
## Description
This issue aims to update the `Single sign-on` section for 4.3 according to the doc about this unit.

## Tasks 1
- [x] Update the `Single sing on` section
- [x] Branch: `5830-update-sso-4.3`
- [x] PR: #5838
- [x] Make a complete review
- [x] Ask for a review

## Tasks 2
- [x] Update the `Single sing on` section
- [x] Branch: `5830-update-sso-4.3-b`
- [x] PR: #5868
- [x] Make a complete review
- [x] Ask for a review
