### ISSUE TITLE
Wazuh 4.4.0 release notes and versions update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5839]
## Description
This issue aims to create the Wazuh v4.4 release notes and versions update throughout the documentation.

## Task 1 - Create the 4.4 Release notes:
- [x] Branch `5839-4.4-release-notes`
- [x] PR #5840  
- [x] Create the 4.4 Release notes
- [x] Add issues:
    - [x] Add issues from wazuh/wazuh
    - [x] Add issues from wazuh/wazuh-dashboard
    - [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [x] Add issues from wazuh/wazuh-splunk
    - [x] Add issues from wazuh/wazuh-packages
- [x] Make a versions update
- [x] Correct and improve issues texts
- [x] Create Highlights
    - [x] Review Highlights with the team
    - [x] Add images to the Highlights
- [x] Make a complete review
- [x] Ask to review and merge

## Task 2 - Make changes to Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-changes`
- [x] PR: #5878
- [x] Make changes to Wazuh 4.4.0 release notes
- [x]  Make a complete review
- [x]  Ask to review and merge

## Task 3 - Review and adjust the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-review`
- [x] PR: #5908
- [x] Review and adjust the Wazuh 4.4.0 release notes
- [x] Make a complete review
- [x] Ask to review and merge

## Task 4 - Update the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-update`
- [x] PR: #5919
- [x] Update the Wazuh 4.4.0 release notes
- [x] Branch: `5839-4.4-release-note-update-v2`
- [x] PR: #5921
- [x] Review the Wazuh 4.4.0 release notes
- [x] Ask to review and merge

## Task 5 - Update the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-update-v3`
- [x] PR: #5945
- [x] Update the Wazuh 4.4.0 release notes
- [x] Ask to review and merge

## Task 6 - Update the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-update-v4`
- [x] PR: #5992
- [x] Update the Wazuh 4.4.0 release notes
- [x] Ask to review and merge

## Task 7 - Update the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-update-v5`
- [x] PR: #5993
- [x] Update the Wazuh 4.4.0 release notes
- [x] Ask to review and merge

## Task 8 - Update the Wazuh 4.4.0 release notes:
- [x] Branch: `5839-4.4-release-note-update-v6`
- [x] PR: #5999
- [x] Update the Wazuh 4.4.0 release notes
- [x] Ask to review and merge
