### ISSUE TITLE
Update Single sign-on OpenSearch Version

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5842]
## Description
This issue aims to update the `Single sign-on` OpenSearch Version.

## Tasks
- [ ] Work with the Google doc: Single Sign On v4.4
- [ ] Branch: 
- [ ] PR: 
- [ ] Update the `Single sign-on` OpenSearch Version
- [ ] Make a complete review
- [ ] Ask for a review
