### ISSUE TITLE
Adjust Wazuh 4.3.0 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5845]
## Description
This issue aims to adjust Wazuh 4.3.0 release notes.

## Tasks
- [x] Branch: `5845-adjust-4.3.0-release-notes`
- [x] PR: #5846
- [x] Adjust Wazuh 4.3.0 release notes
- [x] Make a complete review
- [x] Ask for a review
