### ISSUE TITLE
Adjust SSO text formats 

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5848]
## Description
This issue aims to Adjust SSO 4.3 and 4.4 text formats.

## Tasks 4.3
- [x] Branch: `5848-adjust-sso-4.3-text-formats`
- [x] PR: #5849
- [x] Adjust SSO 4.3 text formats 
- [x] Make a complete review
- [x] Ask for a review

## Tasks 4.4
- [x] Branch: `5848-adjust-sso-4.4-text-formats`
- [x] PR: #5850
- [x] Adjust SSO 4.4 text formats 
- [x] Make a complete review
- [x] Ask for a review
