### ISSUE TITLE
Add missing tabs to the documentation

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5851]
## Description
With the documentation team, we have detected that are some tabs missing in some sections of the documentation, like the following in [Getting started - RESTful API](https://documentation.wazuh.com/current/user-manual/api/getting-started.html):
![image](https://user-images.githubusercontent.com/85168963/209973137-e6c3855e-ca7f-4df2-914f-c9005bc982f2.png)

This issue aims to add missing tabs to the documentation as the following example:
```
.. tabs::

   .. group-tab:: Systemd

      .. code-block:: console

         # systemctl restart filebeat

   .. group-tab:: SysV init

      .. code-block:: console

         # service filebeat restart
```

## Tasks
- [x] Branch: `5851-add-missing-tabs`
- [x] PR: #5853
- [x] Add missing tabs to the documentation 
- [x] Do a complete review
- [x] Ask for a review
