### ISSUE TITLE
Update section Single sign-on for 4.4

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5869]
## Description
This issue aims to update the `Single sign-on` section for 4.4 according to the doc about this unit.

## Tasks 
- [ ] Update the `Single sing on` section
- [ ] Branch: 
- [ ] PR: 
- [ ] Make a complete review
- [ ] Ask for a review
