### ISSUE TITLE
Add new section: Configuring third-party SSL certificates

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5890]
## Description
This issue aims to add the new section `Configuring third-party SSL certificates` in [User manual](https://documentation.wazuh.com/current/user-manual/index.html) / [Wazuh dashboard](https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/index.html) / according to the new Google doc.

## Tasks
- [x] Work with the new Google doc: `Configuring third-party SSL certificates` 
- [x] Branch: `5890-configuring-third-party-ssl-certificates`
- [x] PR: #5891
- [x] Add the new section `Configuring third-party SSL certificates` 
- [x] Make a complete review
- [x] Ask for a review
