### ISSUE TITLE
4.4.0 images update

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5894]
## Description
This issue aims to list and edit the images that need to be updated for 4.4.0. The updated images should reflect all the Wazuh 4.4.0 dashboard components.

##  Task 1 - Review images:
- [x] Review the images in the following sections of the documentation:
    - [x] Getting started
    - [x] Quickstart
    - [x] Installation guide
    - [x] Installation alternatives
    - [x] Upgrade guide
    - [x] Migration guide
    - [x] Cloud service
    - [x] User manual
    - [x] Cloud security   
    - [x] Container security 
    - [x] Development
    - [x] Regulatory compliance
    - [x] Learning Wazuh
    - [x] Proof of Concept guide
- [x] Review and compare old and new dashboard details
- [x] Share results with documentation-team
- [x] Ask for images edition to the design team 

##  Images update part 1:
- [x] Branch: `5894-images-update-4.4.0`
- [x] PR: #5909
- [x] Upload new images
    - [x] Getting started
    - [x] Quickstart
    - [x] Installation guide
    - [x] Installation alternatives
    - [x] Upgrade guide
    - [x] Migration guide
    - [x] Cloud service
- [x] Ask to review and merge

##  Images update part 2:
- [x] Branch: `5894-images-update-4.4.0-p2`
- [x] PR: #5916 
- [x] Upload new images
    - [x] User manual
    - [x] Cloud security   
    - [x] Container security 
    - [x]  Development
    - [x] Regulatory compliance
- [x] Ask to review and merge

##  Images update part 3:
- [x] Branch: `5894-images-update-4.4.0-p3`
- [x] PR: #5924
- [x] Upload new images 
    - [x] Learning Wazuh
    - [x] Proof of Concept guide
- [x] Ask to review and merge
