### ISSUE TITLE
Update the section Regulatory compliance

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5947]
## Description
This issue aims to update the `Regulatory compliance` section.

## Tasks
- [x] Branch: `5947-regulatory-compliance-update`
- [x] PR: #5948
- [x] Update the `Regulatory compliance` section
- [x] Ask to review and merge
