### ISSUE TITLE
Update section: Configuring third-party SSL certificates

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5952]
## Description
This issue aims to update the section `Configuring third-party SSL certificates`.

## Stage 1
- [x] Work with the Google doc: `Configuring third-party SSL/TLS certificates on the Wazuh dashboard` 
- [x] Branch: `5952-update-third-party-ssl-certificates`
- [x] PR: #5953
- [x] Update the section `Configuring SSL certificates on the Wazuh dashboard using NGINX` 
- [x] Make a complete review
- [x] Ask for a review

## Stage 2
- [x] Work with the Google doc: `Configuring third-party SSL/TLS certificates on the Wazuh dashboard` 
- [x] Branch: `5952-update-third-party-ssl-certificates-2`
- [x] PR: #5964
- [x] Update the section `Configuring SSL certificates on the Wazuh dashboard using NGINX` 
- [x] Make a complete review
- [x] Ask for a review
