### ISSUE TITLE
4.4.0 images update - Adjust SEO

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5957]
## Description
This issue aims to adjust the images' SEO details. As we have more than five hundred images in our documentation, we will distribute this issue in several parts. 

## Tasks:
- Adjust SEO
- Improve images file names
- Add `title` and  `alt` attribute to images ([link](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image))

## Part 1:
- [x] Branch: `5894-images-update-4.4.0-seo`
- [x] PR: #5956
- [x] Do a review
- [x] Ask to review and merge

## Part 2:
- [x] Branch: `5957-images-update-4.4.0-seo-2`
- [x] PR: #5960
- [x] Do a review
- [x] Ask to review and merge

## Part 3:
- [x] Branch: `5957-images-update-4.4.0-seo-3`
- [x] PR: #6016
- [x] Do a review
- [x] Ask to review and merge
