### ISSUE TITLE
Section rework: Security Configuration Assessment

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5971]
## Description
This issue aims to rework the section `Security Configuration Assessment`.

## Task 1
- [x] Work with the Google doc: `Security Configuration Assessment` 
- [x] Branch: `5971-rework-sca`
- [x] PR: #5973
- [x] Move the new content to the documentation
- [x] Make a complete review
- [x] Ask for review and merge

## Task 2
- [x] Make some adjustments related to Issue #5991
- [x] Branch: `5971-rework-sca-update`
- [x] PR: #5995
- [x] Make a complete review
- [x] Ask for review and merge
