### ISSUE TITLE
New section: Using Wazuh for NIST 800-53 compliance

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#5979]
## Description
This issue aims to create the new section `Using Wazuh for NIST 800-53 compliance`.

## Tasks
- [x] Work with the Google doc: `Using Wazuh for NIST 800-53 compliance` 
- [x] Branch: `5979-nist-800-53-compliance`
- [x] PR: #5983
- [x] Move the new content to the documentation
- [x] Make a complete review
- [x] Ask for review
- [x] Make adjustments
- [x] Ask for review and merge
