### ISSUE TITLE
POC VirusTotal changes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6014]
## Description
This issue aims to make changes in the `POC VirusTotal` section.

## Tasks
- [ ] Work with the Google doc: `Proof of concept guide` 
- [ ] Branch: 
- [ ] PR: 
- [ ] Make a complete review
- [ ] Ask for review and merge
