### ISSUE TITLE
Upgrade guide grammar review

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6022]
## Description
This issue aims to make a grammar review of the `Upgrade guide`:

## 4.4 Tasks:
- [x] Branch: `6022-upgrade-guide-grammar-review`
- [x] PR: #6023
- [x] Perform an editorial and grammar review  of the `Upgrade guide` section
- [x] Make a complete review
- [x] Ask for review and merge

## 4.3 Tasks:
- [x] Branch: `6022-upgrade-guide-grammar-review-4.3`
- [x] PR: #6042
- [x] Perform an editorial and grammar review  of the `Upgrade guide` section
- [x] Make a complete review
- [x] Ask for review and merge
