### ISSUE TITLE
Bump version to 4.4.2 and merge into branches

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-documentation#6024]
## Description
This issue aims to bump the version to 4.4.2 and merge it into branches.

## Tasks
- [x] Bump version to 4.4.2.
- [ ] Merge 4.4.2 into 4.4.
- [ ] Change the base branch in PRs pointing to 4.4.2.
- [ ] Delete branch 4.4.2.
- [ ] Merge branches 4.4 → 4.5 → master.

**Comment by Arcapas** [comment]
Bump version to 4.4.2 with PR #6027

**Comment by Arcapas** [comment]
Bump version to 4.4.2 with PR #6030
