### ISSUE TITLE
Wazuh 4.4.2 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6028]
## Description
This issue aims to create the Wazuh v4.4.2 release notes.

## Tasks 1: `v4.4.2-rc1`
- [x] Branch: `6028-4.4.2-release-notes`
- [x] PR: #6032
- [x] Create the 4.4.2 Release notes
- [x] Add issues:
    - [x] Add issues from wazuh/wazuh
    - [x] Add issues from wazuh/wazuh-dashboard
    - [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [x] Add issues from wazuh/wazuh-splunk
    - [ ] Add issues from wazuh/wazuh-packages
- [x] Correct and improve issues texts
- [x] Make a complete review
- [x] Ask to review and merge

## Tasks 2: `v4.4.2-rc2`
- [x] Branch: `6028-4.4.2-release-notes-2`
- [x] PR: #6108
- [x] Add issues
- [x] Make a complete review
- [x] Ask to review and merge
