### ISSUE TITLE
Wazuh 4.5.0 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6033]
## Description
This issue aims to create the Wazuh v4.4.2 release notes.

## Tasks
- [ ] Branch: 
- [ ] PR: 
- [ ] Create the 4.5.0 Release notes
- [ ] Add issues:
    - [ ] Add issues from wazuh/wazuh
    - [ ] Add issues from wazuh/wazuh-dashboard
    - [ ] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [ ] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [ ] Add issues from wazuh/wazuh-splunk
    - [ ] Add issues from wazuh/wazuh-packages
- [ ] Make a versions update
- [ ] Correct and improve issues texts
- [ ] Make a complete review
- [ ] Ask to review and merge
