### ISSUE TITLE
Adjust `ossec` issue

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6037]
## Description
This issue aims to adjust `ossec` issue

## Tasks
- [x] Branch: `6037-adjust-ossec-issue`
- [x] PR: #6038
- [x] Adjust `ossec` issue
- [x] Make a review
- [x] Ask to review and merge
