### ISSUE TITLE
Wazuh 4.3.11 release notes

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#6040]
## Description

This issue aims to create the Wazuh v4.3.11 release notes. 

## Tasks
- [x] Create branch. 
- [x] Update the Wazuh version. 
- [x] Create the 4.3.11 Release notes. 
- [x] Add issues:
    - [x] Add issues from wazuh/wazuh
    - [x] Add issues from wazuh/wazuh-dashboard
    - [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [x] Add issues from wazuh/wazuh-splunk
    - [x] Add issues from wazuh/wazuh-packages
 - [x] Create PR: https://github.com/wazuh/wazuh-documentation/pull/6041
 - [x] Create PR for 4.4: #6043
