### ISSUE TITLE
Capabilities sections to be moved

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6044]
## Description
This issue aims to Work on the capabilities sections to be moved.

## Tasks
- [x] Move these capabilities sections:
   - [x] [Fluentd forwarder](https://documentation.wazuh.com/current/user-manual/capabilities/fluent-forwarder.html) move to [User manual > Wazuh server administration](https://documentation.wazuh.com/current/user-manual/manager/index.html)
   - [x] [Agent labels](https://documentation.wazuh.com/current/user-manual/capabilities/labels.html) move to [User manual > Agent management](https://documentation.wazuh.com/current/user-manual/agents/index.html)
   - [x] [Anti-flooding mechanism](https://documentation.wazuh.com/current/user-manual/capabilities/antiflooding.html) move to [User manual > Agent management](https://documentation.wazuh.com/current/user-manual/agents/index.html)
- [x] Branch: `6044-capabilities-sections-to-be-moved`
- [x] PR: #6065
- [x] Make a review
- [x] Ask to review and merge
