### ISSUE TITLE
Section update: File integrity monitoring

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6067]
## Description
This issue aims to update the section `File integrity monitoring`.

## Tasks 1
- [x] Work with the Google doc: `File integrity monitoring` 
- [x] Branch: `6067-fim-section-update`
- [x] PR: #6069
- [x] Move the new content to the documentation
- [x] Make a complete review:
   - [x] Check meta descriptions
   - [x] Check formats
   - [x] Check images
   - [x] Check links
   - [x] Check redirects
- [x] Ask for review and merge
 
## Tasks 2
- [x] Branch: `6067-fim-section-changes`
- [x] PR: #6080
- [x] Remove the `Auditing who-data` section
- [x] Make a complete review
- [x] Ask for review and merge
