### ISSUE TITLE
Section update: Monitoring system calls

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6085]
## Description
This issue aims to update the section `Monitoring system calls`.

## Tasks
- [ ] Work with the Google doc: `Monitoring system calls` 
- [ ] Branch: 
- [ ] PR: 
- [ ] Move the new content to the documentation
- [ ] Make a complete review:
   - [ ] Check meta descriptions
   - [ ] Check formats
   - [ ] Check images
   - [ ] Check links
   - [ ] Check redirects
- [ ] Ask for review and merge

**Comment by Arcapas** [comment]
Issue created by mistake for GitHub site failure.
