### ISSUE TITLE
Section update: File integrity monitoring

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6091]
## Description
This issue aims to update the section `File integrity monitoring`.

## Tasks 1: Update `4.4` Who-data monitoring on Windows
- [x] Work with the Google doc: `File integrity monitoring` 
- [x] Branch: `6091-update-fim`
- [x] PR: #6093
- [x] Update the 4.4 documentation
- [x] Make a complete review
- [x] Ask for review and merge
 
## Tasks 2: Update `4.5` Windows installation directory monitoring
- [x] Work with the Google doc: `File integrity monitoring 4.5` 
- [x] Branch: `6091-update-fim-4.5`
- [x] PR: #6109
- [x] Update the 4.5 documentation
- [x] Make a complete review
- [x] Ask for review and merge
 
## Tasks 3: Update `4.4` System Access Control List (SACL) in Windows
- [x] Work with the Google doc: `File integrity monitoring 4.4` 
- [x] Branch: `6091-update-fim-4.4`
- [x] PR: #6110
- [x] Update the 4.4 documentation
- [x] Make a complete review
- [x] Ask for review and merge
