### ISSUE TITLE
Section update: Monitoring system calls

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6092]
## Description
This issue aims to update the section `Monitoring system calls`.

## Tasks
- [x] Work with the Google doc: `Monitoring system calls`
- [x] Branch: `6092-update-monitoring-system-calls`
- [x] PR: #6105
- [x] Move the new content to the documentation
- [x] Make a complete review:
   - [x] Check meta descriptions
   - [x] Check formats
   - [x] Check images
   - [x] Check links
   - [x] Check redirects
- [x] Ask for review and merge
