### ISSUE TITLE
Section update: System inventory

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6114]
## Description
This issue aims to update the section `System inventory`.

## Tasks
- [x] Work with the Google doc: `System inventory` 
- [x] Branch: `6114-system-inventory-update`
- [x] PR: #6116
- [x] Update the section `System inventory`
- [x] Make a complete review
- [x] Ask for review and merge
