### ISSUE TITLE
Section rework: Enhancing detection with MITRE ATT&CK framework

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6133]
## Description
This issue aims to make a rework of the section `Enhancing detection with MITRE ATT&CK framework`.

## Tasks
- [x] Branch: `6133-mitre-att&ck-rework`
- [x] PR: #6134
- [x] Update the section `Enhancing detection with MITRE ATT&CK framework`
- [x] Make a complete review
- [x] Ask for review and merge
