### ISSUE TITLE
Section update: Vulnerability detection guide

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6138]
## Description
This issue aims to update the section `Vulnerability detection guide`.

## Tasks
- [ ] Work with the Google doc: `Vulnerability detection guide` 
- [ ] Branch: 
- [ ] PR: 
- [ ] Update the section `Vulnerability detection guide`
- [ ] Check the components:
    - [ ] Check the format
    - [ ] Check images
    - [ ] Check links
    - [ ] Check Notes
    - [ ] Check code blocks
    - [ ] Check XML, YAML, and JSON code
    - [ ] Check the SEO
- [ ] Make a last review
- [ ] Ask for review and merge
