### ISSUE TITLE
Section update: Agentless monitoring

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6139]
## Description
This issue aims to update the section `Agentless monitoring`.

## Tasks
- [x] Work with the Google doc: `Agentless monitoring` 
- [x] Branch: `6139-agentless-monitoring-update`
- [x] PR: #6142
- [x] Update the section `Agentless monitoring`
- [x] Check the components:
    - [x] Check the format
    - [x] Check images
    - [x] Check links
    - [x] Check Notes
    - [x] Check code blocks
    - [x] Check XML, YAML, and JSON code
    - [x] Check the SEO
- [x] Make a last review
- [x] Ask for review and merge
