### ISSUE TITLE
Wazuh 4.4.4 release notes

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#6143]
## Description
This issue aims to create the Wazuh v4.4.4 release notes.

## Tasks 1: `v4.4.4-rc1`
- [x] Branch: `6143-4.4.4-release-notes`
- [x] PR: #6144
- [x] Create the 4.4.4 Release notes
- [x] Add issues:
    - [x] Add issues from wazuh/wazuh
    - [x] Add issues from wazuh/wazuh-dashboard
    - [x] Add issues from wazuh/wazuh-kibana-app 7.10.2
    - [x] Add issues from wazuh/wazuh-kibana-app 7.17.x
    - [x] Add issues from wazuh/wazuh-splunk
    - [x] Add issues from wazuh/wazuh-packages
- [x] Correct and improve issues texts
- [x] Make a complete review
- [x] Ask to review and merge
