### ISSUE TITLE
Wazuh 4.4.5 release notes

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#6224]
This issue aims to create the Wazuh 4.4.5 release notes.

## Tasks: 
Review the following change logs and add items if available: 
- [x] wazuh/wazuh
- [x] wazuh/wazuh-dashboard
- [x] wazuh/wazuh-kibana-app 7.10.2
- [x] wazuh/wazuh-kibana-app 7.17.x
- [x] wazuh/wazuh-splunk
- [x] wazuh/wazuh-packages
