### ISSUE TITLE
Wazuh 4.5.0 release notes

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#6269]
## Description

This issue aims to create the Wazuh 4.5.0 release notes.

## Tasks
- [ ] Add issues from the change logs:
    - [ ] wazuh/wazuh
    - [ ] wazuh/wazuh-dashboard
    - [ ] wazuh/wazuh-kibana-app 7.10.2
    - [ ] wazuh/wazuh-kibana-app 7.17.x
    - [ ] wazuh/wazuh-splunk
    - [ ] wazuh/wazuh-packages
