### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6300]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh-documentation repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh-documentation repository.
- [ ] Create a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.1-alpha1
