### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6301]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh-documentation repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.0
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh-documentation repository.
- [ ] Create a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.0-rc1
