### ISSUE TITLE
Support new stage RC 1 for 4.5.1 in wazuh-documentation repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#6338]
## Description

This issue attempts to support a new stage RC 1 for 4.5.1 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-rc1 from branch 4.5.1 on wazuh-documentation repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.1-rc1

**Comment by javimed** [comment]
https://documentation-dev.wazuh.com/v4.5.1-rc1/
