### ISSUE TITLE
Support new stage RC 1 for 4.5.2 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6383]
## Description

This issue attempts to support a new stage RC 1 for 4.5.2 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2
- [x] Create tag v4.5.2-rc1 from branch 4.5.2 on wazuh-documentation repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.2-rc1
- [ ] Upload docs to https://documentation-dev.wazuh.com/v4.5.2-rc1/
