### ISSUE TITLE
Wazuh 4.5.2 release notes

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#6385]
## Description

This issue aims to create the Wazuh 4.5.2 release notes.

## Tasks

- [x] Add changes from the following changelogs:
    - [x] [wazuh/wazuh](https://github.com/wazuh/wazuh/blob/v4.5.2-rc1/CHANGELOG.md)
    - [x] [wazuh/wazuh-kibana-app - Wazuh dashboard](https://github.com/wazuh/wazuh-kibana-app/blob/v4.5.2-2.6.0-rc1/CHANGELOG.md)
    - [x] [wazuh/wazuh-kibana-app - ELK](https://github.com/wazuh/wazuh-kibana-app/blob/v4.5.2-7.17.12-rc1/CHANGELOG.md)
    - [x] [wazuh/wazuh-splunk](https://github.com/wazuh/wazuh-splunk/blob/v4.5.2-8.2-rc1/CHANGELOG.md)
    - [x] [wazuh/wazuh-packages](https://github.com/wazuh/wazuh-packages/blob/v4.5.2-rc1/CHANGELOG.md)
