### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6395]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh-documentation repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.6.0-alpha1.
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.6.0-alpha1/index.html
