### ISSUE TITLE
Support new stage RC 2 for 4.5.2 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6423]
## Description

This issue attempts to support a new stage RC 2 for 4.5.2 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2 (if applicable).
- [x] Create tag v4.5.2-rc2 from branch 4.5.2 on wazuh-documentation repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.2-rc2.
- [ ] Bump revision for branch 4.5.2 on wazuh-documentation repository. (Not applicable)
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.5.2-rc2/

**Comment by s-ocando** [comment]
## Tasks
- [x] Delete old tag and pre-release. 
- [ ] Ensure changelog is updated for 4.5.2 (if applicable).
- [ ] Create tag v4.5.2-rc2 from branch 4.5.2 on wazuh-documentation repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.2-rc2.
- [ ] Upload docs to https://documentation-dev.wazuh.com/v4.5.2-rc2/
