### ISSUE TITLE
Update the recommended system list for the Wazuh central components

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-documentation#6456]
## Description

It is necessary to update the recommended system list for the central components of Wazuh.
Currently, these systems are the following:
![image](https://github.com/wazuh/wazuh-documentation/assets/72193239/aa590d76-d09b-4bb9-9a70-f7cac38a992a)

This list must be updated with these recommended systems, and check that all the Wazuh central components can be installed and work correctly.
![image](https://github.com/wazuh/wazuh-documentation/assets/72193239/4f66d788-752e-45ed-8f9b-6bf0322e2124)

## Tasks

- [ ] Install the central components in every system.
- [ ] Check that the central components work correctly and no errors are generated.
- [ ] Update the recommended system list in the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html#recommended-operating-systems).

**Comment by Deblintrake09** [comment]
## Update

<details><summary>Centos 7 </summary>

- Install central components using Quickstart script
```
# curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -o
04/12/2023 16:27:21 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.0
04/12/2023 16:27:21 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/12/2023 16:27:23 INFO: --- Removing existing Wazuh installation ---
04/12/2023 16:27:23 INFO: Removing Wazuh manager.
04/12/2023 16:27:40 INFO: Wazuh manager removed.
04/12/2023 16:27:40 INFO: Removing Wazuh indexer.
04/12/2023 16:27:42 INFO: Wazuh indexer removed.
04/12/2023 16:27:42 INFO: Removing Filebeat.
04/12/2023 16:27:43 INFO: Filebeat removed.
04/12/2023 16:27:43 INFO: Removing Wazuh dashboard.
04/12/2023 16:27:51 INFO: Wazuh dashboard removed.
04/12/2023 16:27:51 INFO: Installation cleaned.
04/12/2023 16:27:55 INFO: Wazuh web interface port will be 443.
04/12/2023 16:27:57 INFO: Wazuh repository added.
04/12/2023 16:27:57 INFO: --- Configuration files ---
04/12/2023 16:27:57 INFO: Generating configuration files.
04/12/2023 16:27:58 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
04/12/2023 16:27:58 INFO: --- Wazuh indexer ---
04/12/2023 16:27:58 INFO: Starting Wazuh indexer installation.
04/12/2023 16:28:59 INFO: Wazuh indexer installation finished.
04/12/2023 16:28:59 INFO: Wazuh indexer post-install configuration finished.
04/12/2023 16:28:59 INFO: Starting service wazuh-indexer.
04/12/2023 16:29:11 INFO: wazuh-indexer service started.
04/12/2023 16:29:11 INFO: Initializing Wazuh indexer cluster security settings.
04/12/2023 16:29:22 INFO: Wazuh indexer cluster initialized.
04/12/2023 16:29:22 INFO: --- Wazuh server ---
04/12/2023 16:29:22 INFO: Starting the Wazuh manager installation.
04/12/2023 16:30:00 INFO: Wazuh manager installation finished.
04/12/2023 16:30:00 INFO: Starting service wazuh-manager.
04/12/2023 16:30:12 INFO: wazuh-manager service started.
04/12/2023 16:30:12 INFO: Starting Filebeat installation.
04/12/2023 16:30:20 INFO: Filebeat installation finished.
04/12/2023 16:30:21 INFO: Filebeat post-install configuration finished.
04/12/2023 16:30:21 INFO: Starting service filebeat.
04/12/2023 16:30:21 INFO: filebeat service started.
04/12/2023 16:30:21 INFO: --- Wazuh dashboard ---
04/12/2023 16:30:21 INFO: Starting Wazuh dashboard installation.
04/12/2023 16:31:38 INFO: Wazuh dashboard installation finished.
04/12/2023 16:31:38 INFO: Wazuh dashboard post-install configuration finished.
04/12/2023 16:31:38 INFO: Starting service wazuh-dashboard.
04/12/2023 16:31:38 INFO: wazuh-dashboard service started.
04/12/2023 16:31:59 INFO: Initializing Wazuh dashboard web application.
04/12/2023 16:32:00 INFO: Wazuh dashboard web application initialized.
04/12/2023 16:32:00 INFO: --- Summary ---
04/12/2023 16:32:00 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: **********************************
04/12/2023 16:32:00 INFO: Installation finished.
```

- Check logs
```
# cat /var/ossec/logs/ossec.log | grep error

```

- Check UI starts properly
![image](https://github.com/wazuh/wazuh-documentation/assets/14501079/5a1e363d-00e3-42a4-94e9-93f7513a01ad)
![image](https://github.com/wazuh/wazuh-documentation/assets/14501079/67c7db6d-812d-483c-95ac-6e54dea83ec3)


</details>

<details><summary>Centos 7 </summary>

- Install central components using Quickstart script
```
```

- Check logs
```
```

- Check UI starts properly
![image](https://github.com/wazuh/wazuh-documentation/assets/14501079/5a1e363d-00e3-42a4-94e9-93f7513a01ad)
![image](https://github.com/wazuh/wazuh-documentation/assets/14501079/67c7db6d-812d-483c-95ac-6e54dea83ec3)


</details>

**Comment by Deblintrake09** [comment]
## Research conclusion

- Central components can be installed on most of the proposed OSs, but are not instantly recognized by the Installation script and require the usage of `-i` parameter to ignore system healthchecks.
   - This should be checked and updating the script would be a good option so it recognizes the OSs and health checks can be done on those systems.

**Comment by Deblintrake09** [comment]
This Issue has been blocked until https://github.com/wazuh/wazuh-qa/issues/4495 is completed, as it is related.

**Comment by rauldpm** [comment]
We need to review the scope of this issue and its objective after a call with @fcaffieri and @davidcr01, the original scope is to update the recommended systems

**Comment by rauldpm** [comment]
To be done in `Bulletproof deployability tier 2`
