### ISSUE TITLE
Support new stage RC 1 for 4.5.3 in wazuh-documentation repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#6534]
## Description

This issue attempts to support a new stage RC 1 for 4.5.3 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] Bump revision for branch 4.5.3 on wazuh-documentation repository.
- [x] Create tag v4.5.3-rc1 from branch 4.5.3 on wazuh-documentation repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.5.3-rc1.
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.5.3-rc1.
