### ISSUE TITLE
Support new stage RC 2 for 4.6.0 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6675]
## Description

This issue attempts to support a new stage RC 2 for 4.6.0 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [ ] Bump revision for branch 4.6.0 on wazuh-documentation repository.
- [x] Create tag v4.6.0-rc2 from branch 4.6.0 on wazuh-documentation repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.6.0-rc2.
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.6.0-rc2/

**Comment by javimed** [comment]
### Support new stage for v4.6.0-rc2
#### Upward merging to carry latest production changes to the new stage
- [X] Create upward merging PRs up to `4.6.0`.
  - [ ] Merge upward merging PRs.

#### Staging preliminary tasks
- [ ] Check `4.6.0` documentation `CHANGELOG.md`. Create a PR to update it if necessary.
  - [ ] Merge PR updating `CHANGELOG.md`.
- [ ] Draft a new `Wazuh v4.6.0 RC 2` GitHub pre-release using `CHANGELOG.md`.
- [ ] Review changelogs for the following repositories.
  - [ ] `wazuh/wazuh`
  - [ ] `wazuh/wazuh-dasboard-plugins`
  - [ ] `wazuh/wazuh-packages`
- [ ] Check `4.6.0` release notes in documentation. Create a PR to update them if necessary.
  - [ ] Merge PR updating release notes in documentation.

#### Staging
- [ ] Create tag `v4.6.0-rc2` from `4.6.0` branch.
- [ ] Select tag `v4.6.0-rc2` in GitHub releases and publish the new `4.6.0` GitHub pre-release.
- [ ] Upload docs to https://documentation-dev.wazuh.com/v4.6.0-rc2/.
