### ISSUE TITLE
Update Wazuh Manager supported OS since 4.8.0

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#6764]
## Description

Since 4.8.0, the next OS were deprecated for **Wazuh Manager ONLY**

- CentOS 6
- RHEL 6
- Debian 7 
- Ubuntu 12.04
- Oracle Linux 6

New OS baselines are

- CentOS 7
- RHEL 7
- Debian 8
- Ubuntu 13.04
- Oracle Linux 7

## Tasks

- [x] Track the places where those OS and Wazuh Managers should be fixed
  - [x] In case it's a PoC/Use case, validate it with the OS
- [x] Update found OS references

**Comment by ncvicchi** [comment]
#6811 merged
