### ISSUE TITLE
Wazuh 3.7.1 release documentation

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#677]
Several tasks are needed in order to prepare the documentation for the next release, Wazuh 3.7.1.

Each task has its related PR (if it exists).

### Current tasks

- [x] Add release notes. (#678, merged)
- [x] Update documentation links for 3.7.1. (#678, merged)
- [x] Update OVA documentation. (#678, merged)
- [x] Update packages lists checksums. (#678, merged)
- [x] Merge the contents from `3.7.1` branch into `3.7`. (#698, merged)

**Comment by JuanjiJG** [comment]
### December 3rd Update:

The PR #690 has been reviewed and merged as part of this next release.

**Comment by JuanjiJG** [comment]
Wazuh 3.7.1 is out, so I'll proceed to close this issue.

Regards,
Juanjo
