### ISSUE TITLE
Support new stage Alpha 1 for 4.8.0 in wazuh-documentation repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#6827]
## Description

This issue attempts to support a new stage Alpha 1 for 4.8.0 in the wazuh-documentation repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-documentation repository.
- [x] Create tag v4.8.0-alpha1 from branch 4.8.0 on wazuh-documentation repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.8.0-alpha1.
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.8.0-alpha1/

**Comment by javimed** [comment]
### Support new stage for vX.Y.Z-PREREL
#### Upward merging to carry latest production changes to the new stage
- [ ] Create upward merging PRs up to `X.Y.Z`.
  - [ ] If created, merge upward merging PRs.

#### Staging preliminary tasks
- [ ] Check `X.Y.Z` documentation `CHANGELOG.md`. Create a PR to update it if necessary.
  - [ ] If created, merge PR updating `CHANGELOG.md`.
- [ ] Draft a new `Wazuh vX.Y.Z PRE_REL` GitHub pre-release using `CHANGELOG.md`.
- [ ] Review changelogs for the following repositories.
  - [ ] `wazuh/wazuh`
  - [ ] `wazuh/wazuh-dasboard-plugins`
  - [ ] `wazuh/wazuh-packages`
- [ ] Check `X.Y.Z` release notes in documentation. Create a PR to update them if necessary.
  - [ ] if created, merge PR updating release notes in documentation.

#### Staging
- [ ] Create tag `vX.Y.Z-PREREL` from `X.Y.Z` branch.
- [ ] Select tag `vX.Y.Z-PREREL` in GitHub releases and publish the new `X.Y.Z` GitHub pre-release.
- [ ] Upload docs to https://documentation-dev.wazuh.com/vX.Y.Z-PREREL/.
