### ISSUE TITLE
Minor documentation typos

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#688]
This task includes issues about documentation typos that can be included on a single pull request.

### Pending tasks
- [ ] Bad references in Configuring email alerts section (#687)
- [ ] Fix wrong path in OpenSCAP reference documentation (#684)
- [ ] Single bold word in text block (#681)
- [ ] Remove "string" value from "type" attribute in Syscheck "ignore" tag (#679)

**Comment by JuanjiJG** [comment]
Related PR: #767
