### ISSUE TITLE
Update AWS documentation with AWS Security Hub integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-documentation#6900]
# Description

Following the [AWS Security Hub epic](https://github.com/wazuh/wazuh/issues/21209) and once the integration is fully developed in https://github.com/wazuh/wazuh/issues/21166, the AWS module documentation needs to be updated with this new capability.

## Tasks

- [x] Include clear instructions for setting up and configuring the integration, updating the `wodle-s3` reference page accordingly.
- [x] Document any potential issues or limitations.
- [x] Guide troubleshooting and support.

**Comment by fdalmaup** [comment]
# Issue Update

- Started the development of the documentation in the [`enhancement/6900-security-hub-docs` branch](https://github.com/wazuh/wazuh-documentation/tree/enhancement/6900-security-hub-docs). 
- Extended the AWS module reference.
- Added the structure for the new `Amazon Security Hub` page.
