### ISSUE TITLE
Improve Wazuh manager deployment to include the indexer URLs

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7018]
## Description

One of the settings of the new indexer block in the `ossec.conf` file is `indexer.hosts.host`, this setting is specified as:

- https://documentation-dev.wazuh.com/v4.8.0-beta1/user-manual/reference/ossec-conf/indexer.html#hosts

> Wazuh indexer node URL or IP address to connect to. For example, http://172.16.1.11 or 192.168.3.2:9230.

The block code example is:

```
<indexer>
  <enabled>yes</enabled>
  <hosts>
    <host>https://0.0.0.0:9200</host>
  </hosts>
```

We need to set an additional step alongside the keystore values to modify this setting as it will not connect to the indexer node by default, for example:

- https://documentation-dev.wazuh.com/v4.8.0-beta1/installation-guide/wazuh-server/step-by-step.html#installing-the-wazuh-manager

This value change is done in the Wazuh installation assistant to avoid the following error https://github.com/wazuh/wazuh-packages/pull/2808

## Tasks

- [x] Change the Wazuh manager deployment guide to modify the indexer URLs (single and distributed)
- [x] Review the https://documentation-dev.wazuh.com/v4.8.0-beta1/user-manual/reference/ossec-conf/vuln-detector.html documentation and consider if the indexer code block should be removed as the documentation is explicit for Vulnerability Detection and the Indexer block has his own [documentation](https://documentation-dev.wazuh.com/v4.8.0-beta1/user-manual/reference/ossec-conf/indexer.html)
- [x] Review the upgrade guide as it does not specify to change the URLs or the Keystore for the indexer configuration (thanks to @Rebits)
  - https://documentation-dev.wazuh.com/v4.8.0-beta1/upgrade-guide/upgrading-central-components.html
- [x] Review PoC guides, for example:
  - https://documentation-dev.wazuh.com/v4.8.0-beta1/proof-of-concept-guide/poc-vulnerability-detection.html
