### ISSUE TITLE
Install from sources guide uses the development bucket and GitHub branch instead of a tag

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7118]
## Description

References have been found in the Wazuh install from sources referring to packages-dev.wazuh.com instead of packages.wazuh.com, also, branch references have been found and they should refer to the latest tag

![image](https://github.com/wazuh/wazuh-documentation/assets/14913942/44e254fa-6c1a-4e3b-a7df-d26ad74b6318)

We should fix those references

## Tasks

- [ ] Review all Installation from sources guide
- [ ] Change references to packages.wazuh.com
- [ ] Change references to the latest tag
