### ISSUE TITLE
Remove `Wazuh_Ruleset.pdf` references

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7126]
# Description

- We need to remove documentation references about a PDF file called `Wazuh_Ruleset`, a search over the Wazuh repositories shows the following references: [GitHub search](https://github.com/search?q=org%3Awazuh+%22Wazuh_Ruleset.pdf%22&type=code)
  - https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/ruleset/getting-started.rst
- The file must also be removed from AWS storage: https://www.wazuh.com/resources/Wazuh_Ruleset.pdf
- We also need to check if this file is used in other resources, for this we must ask @wazuh/marketing-content team

# Tasks

- [x] Remove file references from 4.8 onwards
- [x] Notify @wazuh/marketing-content team about the file removal
  - Add tasks to this issue or link issues if something else should be done
- [x] ~Validate if this file reference removal should be contemplated in previous versions~
  - Change will be applied from 4.8.0 onwards
  - [x] ~If yes, remove it in the 4.6 branch and previous branches (tags should not be modified)~
- [x] ~Upload new documentation to `documentation.wazuh.com`~

---

- DRI (requester): @davidjiglesias

**Comment by Spades0** [comment]
We can remove this document but we should consider bringing it back in Wazuh v5.

**Comment by rauldpm** [comment]
Update issue, PDF should be removed from 4.8.0 onwards
