### ISSUE TITLE
Update documentation after package migration

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-documentation#7184]
# Description

Hello team,

We have been working on the issue of migrating all the package generation tools from wazuh-packages to wazuh/wazuh:
- Issue related: https://github.com/wazuh/wazuh/issues/21755

After that, we need to update some of the hints and descriptions related to manual package generation.
The usage of some scripts has been modified, so it is necessary to update the corresponding steps and the explanation of the parameters.

## Task list

- [x] [DEB](https://documentation.wazuh.com/current/development/packaging/generate-deb-package.html)
- [x] [RPM](https://documentation.wazuh.com/current/development/packaging/generate-rpm-package.html)
- [x] [macOS](https://documentation.wazuh.com/current/development/packaging/generate-osx-package.html)
- [x] [Windows](https://documentation.wazuh.com/current/development/packaging/generate-windows-package.html)
- [x] [WPK](https://documentation.wazuh.com/current/development/packaging/generate-wpk-package.html)

**Comment by lchico** [comment]
# Update

Started work on DEB and RPM documentation.

**Comment by lchico** [comment]
# Update

Enhanced DEB and RPM documentation.
![image](https://github.com/wazuh/wazuh-documentation/assets/21695385/c116612c-2f9a-4996-b567-52f1878241a5)

**Comment by lchico** [comment]
We've marked this issue as blocked until we're certain no further changes are needed for package generation.

**Comment by mjcr99** [comment]
## Updates
**(15/05/2024)** Reviewing current modifications and verifying if something is missing in the current files.
