### ISSUE TITLE
Add missing dependencies to the Offline Installation Assistant

### ISSUE THREAD

**Issue by CarlosALgit** [wazuh/wazuh-documentation#7928]
# Description
While doing tests in [this issue](https://github.com/wazuh/wazuh-installation-assistant/issues/119), I found that there are dependencies that are not explicitly set as necessary. So if we proceed with the installation, it will fail asking for the installation of those needed dependencies.
This issue is an extension of [this](https://github.com/wazuh/wazuh-documentation/issues/7734) one.

The needed dependencies for each one of the Wazuh central components are the following.

## Wazuh Indexer
- RPM
  - ~~[ ] coreutils~~
- DEB
  - ~~[ ] debconf~~
  - ~~[ ] adduser~~
  - ~~[ ] procps~~
  - ~~[ ] gnupg~~
  - [x] apt-transport-https

## Wazuh Server
- RPM
  - [x] libcap 
- DEB
  - ~~[ ] apt-transport-https~~
  - ~~[ ] libcap2-bin~~
  - ~~[ ] software-properties-common~~
  - ~~[ ] gnupg~~

## Wazuh Dashboard
- RPM
  - ~~[ ] libcap~~
- DEB
  - ~~[ ] debhelper~~
  - ~~[ ] tar~~
  - ~~[ ] curl~~
  - ~~[ ] libcap2-bin~~
  - ~~[ ] gnupg~~
  - ~~[ ] apt-transport-https~~

## Tasks
- [x] Check that the dependencies above are the all needed to perform a Wazuh Offline Installation with the Assistant.
- [x] Add the missing ones, if needed.
