### ISSUE TITLE
Change all references to `wazuh-packages` repository

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh-documentation#7989]
Following the development carried out in [Wazuh packages redesign tier 2](https://github.com/wazuh/wazuh-packages/issues/2904), considering that the `wazuh-packages` repository is going to be deprecated, it is necessary to remove any existing reference to this repository in:

- https://documentation.wazuh.com/4.9/upgrade-guide/upgrading-central-components.html#upgrading-the-wazuh-dashboard
  - https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/upgrade-guide/upgrading-central-components.rst

<details><summary>References</summary>

```
source/upgrade-guide/upgrading-central-components.rst:   To ensure compatibility with the latest Wazuh indexer and Wazuh dashboard, please update manually installed plugins accordingly. For additional information, check the `distribution matrix <https://github.com/wazuh/wazuh-packages/tree/v|WAZUH_CURRENT|#distribution-version-matrix>`__.
source/upgrade-guide/upgrading-central-components.rst:   To ensure compatibility with the latest Wazuh indexer and Wazuh dashboard, please update manually installed plugins accordingly. For additional information, check the `distribution matrix <https://github.com/wazuh/wazuh-packages/tree/v|WAZUH_CURRENT|#distribution-version-matrix>`__.
```

</details>

## Tasks

- [ ] Check all references to `wazuh-packages`.
- [ ] Change the references and adapt them to not use that repository.
- [ ] Check that everything is working properly.
